/* eslint-disable import/prefer-default-export */
/* eslint-disable max-len */
/* eslint-disable comma-dangle */
/* eslint-disable quote-props */
/* eslint-disable quotes */
const ATcoefficients = {
  "Air-carrier sprayer": {
    "key": "Air-carrier sprayer",
    "RF1": 0.2,
    "RF2": 1.6,
    "Life (hr)": 2000,
    "RV1": 0.8554,
    "RV2": 0.1177,
    "RV3": 0,
    "RV4": 0.0029,
    "RV5": 0.1274
  },
  "Bean puller-windrower": {
    "key": "Bean puller-windrower",
    "RF1": 0.2,
    "RF2": 1.6,
    "Life (hr)": 2000,
    "RV1": 0.7194,
    "RV2": 0.1102,
    "RV3": 0,
    "RV4": 0.003,
    "RV5": 0.1213
  },
  "Beet topper/stalk chopper": {
    "key": "Beet topper/stalk chopper",
    "RF1": 0.28,
    "RF2": 1.4,
    "Life (hr)": 1200,
    "RV1": 0.7194,
    "RV2": 0.1102,
    "RV3": 0,
    "RV4": 0.003,
    "RV5": 0.1213
  },
  "Boom type sprayer": {
    "key": "Boom type sprayer",
    "RF1": 0.41,
    "RF2": 1.3,
    "Life (hr)": 1500,
    "RV1": 0.8554,
    "RV2": 0.1177,
    "RV3": 0,
    "RV4": 0.0029,
    "RV5": 0.1274
  },
  "Chisel plow": {
    "key": "Chisel plow",
    "RF1": 0.28,
    "RF2": 1.4,
    "Life (hr)": 2000,
    "RV1": 0.6927,
    "RV2": 0.0703,
    "RV3": 0,
    "RV4": 0.0012,
    "RV5": 0.1223
  },
  "Combine (pulled)": {
    "key": "Combine (pulled)",
    "RF1": 0.12,
    "RF2": 2.3,
    "Life (hr)": 2000,
    "RV1": 1.054,
    "RV2": 0.1865,
    "RV3": 0.0068,
    "RV4": 0.0028,
    "RV5": 0.0847
  },
  "Combine (self propelled)": {
    "key": "Combine (self propelled)",
    "RF1": 0.04,
    "RF2": 2.1,
    "Life (hr)": 3000,
    "RV1": 1.01361018,
    "RV2": 0.174199608,
    "RV3": 0.007696442,
    "RV4": 0.000749051,
    "RV5": 0
  },
  "Combine (self propelled*)": {
    "key": "Combine (self propelled*)",
    "RF1": 0.04,
    "RF2": 2.1,
    "Life (hr)": 3000,
    "RV1": 1.054,
    "RV2": 0.1865,
    "RV3": 0.0068,
    "RV4": 0.0028,
    "RV5": 0.0847
  },
  "Combine (self propelled**)": {
    "key": "Combine (self propelled**)",
    "RF1": 0.04,
    "RF2": 2.1,
    "Life (hr)": 3000,
    "RV1": 1.054,
    "RV2": 0.1865,
    "RV3": 0.0068,
    "RV4": 0.0028,
    "RV5": 0.0847
  },
  "Combine (self propelled***)": {
    "key": "Combine (self propelled***)",
    "RF1": 0.04,
    "RF2": 2.1,
    "Life (hr)": 3000,
    "RV1": 1.01905018,
    "RV2": 0.174199608,
    "RV3": 0.007696442,
    "RV4": 0.000749051,
    "RV5": 0
  },
  "Corn picker sheller": {
    "key": "Corn picker sheller",
    "RF1": 0.14,
    "RF2": 2.3,
    "Life (hr)": 2000,
    "RV1": 1.054,
    "RV2": 0.1865,
    "RV3": 0.0068,
    "RV4": 0.0028,
    "RV5": 0.0847
  },
  "Cotton picker": {
    "key": "Cotton picker",
    "RF1": 0.11,
    "RF2": 1.8,
    "Life (hr)": 3000,
    "RV1": 1.054,
    "RV2": 0.1865,
    "RV3": 0.0068,
    "RV4": 0.0028,
    "RV5": 0.0847
  },
  "Fertilizer spreader": {
    "key": "Fertilizer spreader",
    "RF1": 0.63,
    "RF2": 1.3,
    "Life (hr)": 1200,
    "RV1": 0.8635,
    "RV2": 0.1288,
    "RV3": 0,
    "RV4": 0.0017,
    "RV5": 0.1569
  },
  "Field cultivators": {
    "key": "Field cultivators",
    "RF1": 0.27,
    "RF2": 1.4,
    "Life (hr)": 2000,
    "RV1": 0.6927,
    "RV2": 0.0703,
    "RV3": 0,
    "RV4": 0.0012,
    "RV5": 0.1223
  },
  "Forage blower": {
    "key": "Forage blower",
    "RF1": 0.22,
    "RF2": 1.8,
    "Life (hr)": 1500,
    "RV1": 0.6529,
    "RV2": 0.1511,
    "RV3": 0,
    "RV4": 0.0078,
    "RV5": 0.1235
  },
  "Forage harvester": {
    "key": "Forage harvester",
    "RF1": 0.15,
    "RF2": 1.6,
    "Life (hr)": 2500,
    "RV1": 0.6529,
    "RV2": 0.1511,
    "RV3": 0,
    "RV4": 0.0078,
    "RV5": 0.1235
  },
  "Forage harvester (SP)": {
    "key": "Forage harvester (SP)",
    "RF1": 0.03,
    "RF2": 2,
    "Life (hr)": 4000,
    "RV1": 0.6529,
    "RV2": 0.1511,
    "RV3": 0,
    "RV4": 0.0078,
    "RV5": 0.1235
  },
  "Forage wagons": {
    "key": "Forage wagons",
    "RF1": 0.16,
    "RF2": 1.6,
    "Life (hr)": 2000,
    "RV1": 0.8091,
    "RV2": 0.1109,
    "RV3": 0,
    "RV4": 0.0014,
    "RV5": 0.1267
  },
  "Four wheel drive tractors & crawlers": {
    "key": "Four wheel drive tractors & crawlers",
    "RF1": 0.003,
    "RF2": 2,
    "Life (hr)": 16000,
    "RV1": 0.8641,
    "RV2": 0.1564,
    "RV3": 0.0034,
    "RV4": 0.0046,
    "RV5": 0.086
  },
  "Grain drill": {
    "key": "Grain drill",
    "RF1": 0.32,
    "RF2": 2.1,
    "Life (hr)": 1500,
    "RV1": 1.2211,
    "RV2": 0.1737,
    "RV3": 0,
    "RV4": -0.0017,
    "RV5": 0.1264
  },
  "Heavy Duty disk harrow": {
    "key": "Heavy Duty disk harrow",
    "RF1": 0.18,
    "RF2": 1.7,
    "Life (hr)": 2000,
    "RV1": 0.7194,
    "RV2": 0.1102,
    "RV3": 0,
    "RV4": 0.003,
    "RV5": 0.1213
  },
  "Large rectangular baler": {
    "key": "Large rectangular baler",
    "RF1": 0.1,
    "RF2": 1.8,
    "Life (hr)": 3000,
    "RV1": 0.8091,
    "RV2": 0.1109,
    "RV3": 0,
    "RV4": 0.0014,
    "RV5": 0.1267
  },
  "Large round baler": {
    "key": "Large round baler",
    "RF1": 0.43,
    "RF2": 1.8,
    "Life (hr)": 1500,
    "RV1": 0.8091,
    "RV2": 0.1109,
    "RV3": 0,
    "RV4": 0.0014,
    "RV5": 0.1267
  },
  "Manure handling equipment": {
    "key": "Manure handling equipment",
    "RF1": 0.16,
    "RF2": 1.6,
    "Life (hr)": 2000,
    "RV1": 0.8635,
    "RV2": 0.1288,
    "RV3": 0,
    "RV4": 0.0017,
    "RV5": 0.1569
  },
  "Mech. front wheel drive tractors": {
    "key": "Mech. front wheel drive tractors",
    "RF1": 0.005,
    "RF2": 2,
    "Life (hr)": 16000,
    "RV1": 0.8641,
    "RV2": 0.1564,
    "RV3": 0.0034,
    "RV4": 0.0046,
    "RV5": 0.086
  },
  "Moldboard plows": {
    "key": "Moldboard plows",
    "RF1": 0.29,
    "RF2": 1.8,
    "Life (hr)": 2000,
    "RV1": 0.6927,
    "RV2": 0.0703,
    "RV3": 0,
    "RV4": 0.0012,
    "RV5": 0.1223
  },
  "Mower": {
    "key": "Mower",
    "RF1": 0.46,
    "RF2": 1.7,
    "Life (hr)": 2000,
    "RV1": 0.9023,
    "RV2": 0.0943,
    "RV3": 0,
    "RV4": -0.0004,
    "RV5": 0.1073
  },
  "Mower (rotary)": {
    "key": "Mower (rotary)",
    "RF1": 0.44,
    "RF2": 2,
    "Life (hr)": 2000,
    "RV1": 0.9023,
    "RV2": 0.0943,
    "RV3": 0,
    "RV4": -0.0004,
    "RV5": 0.1073
  },
  "Mower-conditioner": {
    "key": "Mower-conditioner",
    "RF1": 0.18,
    "RF2": 1.6,
    "Life (hr)": 2500,
    "RV1": 0.7243,
    "RV2": 0.1127,
    "RV3": 0,
    "RV4": 0.0034,
    "RV5": 0.1188
  },
  "Mower-conditioner (rotary)": {
    "key": "Mower-conditioner (rotary)",
    "RF1": 0.16,
    "RF2": 2,
    "Life (hr)": 2500,
    "RV1": 0.7243,
    "RV2": 0.1127,
    "RV3": 0,
    "RV4": 0.0034,
    "RV5": 0.1188
  },
  "Mulcher-packer": {
    "key": "Mulcher-packer",
    "RF1": 0.16,
    "RF2": 1.3,
    "Life (hr)": 2000,
    "RV1": 0.7194,
    "RV2": 0.1102,
    "RV3": 0,
    "RV4": 0.003,
    "RV5": 0.1213
  },
  "None": {
    "key": "None",
    "RF1": "",
    "RF2": "",
    "Life (hr)": "",
    "RV1": "",
    "RV2": "",
    "RV3": "",
    "RV4": "",
    "RV5": ""
  },
  "Potato harvester": {
    "key": "Potato harvester",
    "RF1": 0.19,
    "RF2": 1.4,
    "Life (hr)": 2500,
    "RV1": 0.8091,
    "RV2": 0.1109,
    "RV3": 0,
    "RV4": 0.0014,
    "RV5": 0.1267
  },
  "Rectangular baler": {
    "key": "Rectangular baler",
    "RF1": 0.23,
    "RF2": 1.8,
    "Life (hr)": 2000,
    "RV1": 0.8091,
    "RV2": 0.1109,
    "RV3": 0,
    "RV4": 0.0014,
    "RV5": 0.1267
  },
  "Roller packer": {
    "key": "Roller packer",
    "RF1": 0.16,
    "RF2": 1.3,
    "Life (hr)": 2000,
    "RV1": 0.7194,
    "RV2": 0.1102,
    "RV3": 0,
    "RV4": 0.003,
    "RV5": 0.1213
  },
  "Rotary hoe": {
    "key": "Rotary hoe",
    "RF1": 0.23,
    "RF2": 1.4,
    "Life (hr)": 2000,
    "RV1": 0.6927,
    "RV2": 0.0703,
    "RV3": 0,
    "RV4": 0.0012,
    "RV5": 0.1223
  },
  "Rotary tiller": {
    "key": "Rotary tiller",
    "RF1": 0.36,
    "RF2": 2,
    "Life (hr)": 1500,
    "RV1": 0.7194,
    "RV2": 0.1102,
    "RV3": 0,
    "RV4": 0.003,
    "RV5": 0.1213
  },
  "Row crop cultivator": {
    "key": "Row crop cultivator",
    "RF1": 0.17,
    "RF2": 2.2,
    "Life (hr)": 2000,
    "RV1": 0.6927,
    "RV2": 0.0703,
    "RV3": 0,
    "RV4": 0.0012,
    "RV5": 0.1223
  },
  "Row crop planter": {
    "key": "Row crop planter",
    "RF1": 0.32,
    "RF2": 2.1,
    "Life (hr)": 1500,
    "RV1": 0.8554,
    "RV2": 0.1177,
    "RV3": 0,
    "RV4": 0.0029,
    "RV5": 0.1274
  },
  "Side delivery rake": {
    "key": "Side delivery rake",
    "RF1": 0.17,
    "RF2": 1.4,
    "Life (hr)": 2500,
    "RV1": 0.8091,
    "RV2": 0.1109,
    "RV3": 0,
    "RV4": 0.0014,
    "RV5": 0.1267
  },
  "Skid-steer loader": {
    "key": "Skid-steer loader",
    "RF1": 0.007,
    "RF2": 2,
    "Life (hr)": 3000,
    "RV1": 0.7275,
    "RV2": 0.0806,
    "RV3": 0.0025,
    "RV4": 0.004,
    "RV5": 0.0812
  },
  "Spring tooth harrow": {
    "key": "Spring tooth harrow",
    "RF1": 0.27,
    "RF2": 1.4,
    "Life (hr)": 2000,
    "RV1": 0.6927,
    "RV2": 0.0703,
    "RV3": 0,
    "RV4": 0.0012,
    "RV5": 0.1223
  },
  "Sugar beet harvester": {
    "key": "Sugar beet harvester",
    "RF1": 0.59,
    "RF2": 1.3,
    "Life (hr)": 1500,
    "RV1": 0.7194,
    "RV2": 0.1102,
    "RV3": 0,
    "RV4": 0.003,
    "RV5": 0.1213
  },
  "Tandem disk harrow": {
    "key": "Tandem disk harrow",
    "RF1": 0.18,
    "RF2": 1.7,
    "Life (hr)": 2000,
    "RV1": 0.7194,
    "RV2": 0.1102,
    "RV3": 0,
    "RV4": 0.003,
    "RV5": 0.1213
  },
  "Total mixed ration mixer wagons": {
    "key": "Total mixed ration mixer wagons",
    "RF1": 0.015,
    "RF2": 1.6,
    "Life (hr)": 5000,
    "RV1": 0.8091,
    "RV2": 0.1109,
    "RV3": 0,
    "RV4": 0.0014,
    "RV5": 0.1267
  },
  "Two wheel drive tractors": {
    "key": "Two wheel drive tractors",
    "RF1": 0.1,
    "RF2": 1.3,
    "Life (hr)": 1500,
    "RV1": 0.8554,
    "RV2": 0.1177,
    "RV3": 0,
    "RV4": 0.0029,
    "RV5": 0.1274
  },
  "Two wheel drive tractors, 81-120 HP": {
    "key": "Two wheel drive tractors, 81-120 HP",
    "RF1": 0.007,
    "RF2": 2,
    "Life (hr)": 12000,
    "RV1": 0.8469,
    "RV2": 0.1103,
    "RV3": 0.0036,
    "RV4": 0.0042,
    "RV5": 0.1099
  },
  "Two wheel drive tractors, 121-145 HP": {
    "key": "Two wheel drive tractors, 121-145 HP",
    "RF1": 0.007,
    "RF2": 2,
    "Life (hr)": 12000,
    "RV1": 0.8304,
    "RV2": 0.1207,
    "RV3": 0.0021,
    "RV4": 0.0048,
    "RV5": 0.1074
  },
  "Two wheel drive tractors, 146+ HP TWD": {
    "key": "Two wheel drive tractors, 146+ HP TWD",
    "RF1": 0.007,
    "RF2": 2,
    "Life (hr)": 12000,
    "RV1": 0.8664,
    "RV2": 0.1502,
    "RV3": 0.0033,
    "RV4": 0.0055,
    "RV5": 0.1098
  },
  "Two wheel drive tractors, under 80 HP": {
    "key": "Two wheel drive tractors, under 80 HP",
    "RF1": 0.007,
    "RF2": 2,
    "Life (hr)": 12000,
    "RV1": 0.8493,
    "RV2": 0.0966,
    "RV3": 0.0059,
    "RV4": 0.0038,
    "RV5": 0.1062
  },
  "Wagon": {
    "key": "Wagon",
    "RF1": 0.19,
    "RF2": 1.3,
    "Life (hr)": 3000,
    "RV1": 0.8091,
    "RV2": 0.1109,
    "RV3": 0,
    "RV4": 0.0014,
    "RV5": 0.1267
  },
  "Windrower (SP)": {
    "key": "Windrower (SP)",
    "RF1": 0.06,
    "RF2": 2,
    "Life (hr)": 3000,
    "RV1": 0.7243,
    "RV2": 0.1127,
    "RV3": 0,
    "RV4": 0.0034,
    "RV5": 0.1188
  }
};

const ATrates = {
  "conversion": {
    "key": "conversion",
    "description": "Acres Conversion factor (=43560 ft2/ac * mi/5280ft)",
    "value": 8.25
  },
  "deflator": {
    "key": "deflator",
    "description": "GDP implicit price deflator, 2020 4th quarter",
    "value": 114.4
  },
  "deflator1996": {
    "key": "deflator1996",
    "description": "GDP implicit price deflator, 1996",
    "value": 76.783
  },
  "forecast": {
    "key": "forecast",
    "description": "2020 U.S. net farm income forecast ($ billions)",
    "value": 111.4
  },
  "fuel": {
    "key": "fuel",
    "description": "Fuel price, $/gallon",
    "value": 3.5
  },
  "horsepower": {
    "key": "horsepower",
    "description": "Self propelled assumed horsepower (for fuel calcs)",
    "value": 80
  },
  "inflation": {
    "key": "inflation",
    "description": "Inflation Rate, % per year",
    "value": 0
  },
  "insurance": {
    "key": "insurance",
    "description": "Insurance Rate",
    "value": 0.0085
  },
  "interest": {
    "key": "interest",
    "description": "Interest Rate, % of average investment",
    "value": 0.08
  },
  "K2O": {
    "key": "K2O",
    "description": "$ per pound of K2O",
    "value": 0.53
  },
  "lubrication": {
    "key": "lubrication",
    "description": "Lubrication cost, % of fuel",
    "value": 0.1
  },
  "Nitrogen": {
    "key": "Nitrogen",
    "description": "$ per pound of N",
    "value": 0.61
  },
  "P2O5": {
    "key": "P2O5",
    "description": "$ per pound of P2O5",
    "value": 0.69
  },
  "projected": {
    "key": "projected",
    "description": "Real Net Farm Income projected at trade-in, in $ billion 1996 dollars",
    "value": 74.76945979
  },
  "property": {
    "key": "property",
    "description": "Property taxes",
    "value": 0.005
  },
  "skilled": {
    "key": "skilled",
    "description": "Skilled Labor Rate $/hr.",
    "value": 20
  },
  "storage": {
    "key": "storage",
    "description": "Storage Cost/Sq. Foot of Space",
    "value": 0.969218963
  }
};

const ATcostDefaults = {
  "Aerial seeding": {
    "key": "Aerial seeding",
    "cost": 14,
    "Notes": "Estimated from 2023 Iowa Custom Rate Survey data"
  },
  "aerial spraying": {
    "key": "aerial spraying",
    "cost": 11,
    "Notes": "Estimated from 2023 Iowa Custom Rate Survey data"
  },
  "Anhydrous ammonia injection": {
    "key": "Anhydrous ammonia injection",
    "cost": 14.75,
    "Notes": "Estimated from 2023 Iowa Custom Rate Survey data"
  },
  "drone seeding": {
    "key": "drone seeding",
    "cost": 16,
    "Notes": "placeholder number"
  },
  "drone spraying": {
    "key": "drone spraying",
    "cost": 15,
    "Notes": "placeholder number"
  },
  "Dry Fertilizer application": {
    "key": "Dry Fertilizer application",
    "cost": 6.75,
    "Notes": "Estimated from 2023 Iowa Custom Rate Survey data"
  },
  "Herbicide application": {
    "key": "Herbicide application",
    "cost": 8,
    "Notes": "Estimated from 2023 Iowa Custom Rate Survey data"
  },
  "Liquid fertilizer application": {
    "key": "Liquid fertilizer application",
    "cost": 8,
    "Notes": "Estimated from 2023 Iowa Custom Rate Survey data"
  },
  "Planting": {
    "key": "Planting",
    "cost": 20,
    "Notes": "Estimated from 2023 Iowa Custom Rate Survey data"
  },
  "Roller": {
    "key": "Roller",
    "cost": 15,
    "Notes": "Calculated full cost of 6 row CC roller in CC DST mockup 7-20-22"
  },
  "Seedbed preparation": {
    "key": "Seedbed preparation",
    "cost": 18,
    "Notes": "Estimated from 2023 Iowa Custom Rate Survey data"
  }
};

const ATherbicides = {
  "2,4-D": {
    "key": "2,4-D",
    "Rate": 1,
    "Unit (rate)": "lb/acre",
    "Cost ($)": "5",
    "Unit (cost)": "lb"
  },
  "atrazine": {
    "key": "atrazine",
    "Rate": 2,
    "Unit (rate)": "lb/acre",
    "Cost ($)": "4",
    "Unit (cost)": "lb"
  },
  "dicamba": {
    "key": "dicamba",
    "Rate": 3,
    "Unit (rate)": "lb/acre",
    "Cost ($)": "3",
    "Unit (cost)": "lb"
  },
  "glyphosate": {
    "key": "glyphosate",
    "Rate": 4,
    "Unit (rate)": "lb/acre",
    "Cost ($)": "2",
    "Unit (cost)": "lb"
  },
  "liberty": {
    "key": "liberty",
    "Rate": 5,
    "Unit (rate)": "lb/acre",
    "Cost ($)": "1",
    "Unit (cost)": "lb"
  }
};

const ATimplements = {
  "Air Seeder Drill w/Cart; 52 Ft": {
    "key": "Air Seeder Drill w/Cart; 52 Ft",
    "type": "Planting",
    "name": "Air Seeder Drill w/Cart",
    "size1": 52,
    "unit1": "Ft",
    "default power unit": "260 HP MFWD Tractor",
    "purchase price 2020": 263500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 80,
    "default ASABE category": "Grain drill",
    "field speed (m/h)": 5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 270,
    "size2": "",
    "unit2": ""
  },
  "Boom Sprayer, Pull-Type; 90 Ft": {
    "key": "Boom Sprayer, Pull-Type; 90 Ft",
    "type": "Chemical",
    "name": "Boom Sprayer, Pull-Type",
    "size1": 90,
    "unit1": "Ft",
    "default power unit": "130 HP MFWD Tractor",
    "purchase price 2020": 55000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 25,
    "default ASABE category": "Boom type sprayer",
    "field speed (m/h)": 6.5,
    "field efficiency": 0.65,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.25,
    "labortype": "Skilled",
    "shed (ft^2)": 400,
    "size2": "",
    "unit2": ""
  },
  "Boom Sprayer, Self-Propelled; 90 Ft": {
    "key": "Boom Sprayer, Self-Propelled; 90 Ft",
    "type": "Chemical",
    "name": "Boom Sprayer, Self-Propelled",
    "size1": 90,
    "unit1": "Ft",
    "default power unit": "130 Self Propelled",
    "purchase price 2020": 300500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Two wheel drive tractors",
    "field speed (m/h)": 7,
    "field efficiency": 0.65,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.25,
    "labortype": "Skilled",
    "shed (ft^2)": 200,
    "size2": "",
    "unit2": ""
  },
  "Chisel Plow, Front Dsk; 16.3 Ft": {
    "key": "Chisel Plow, Front Dsk; 16.3 Ft",
    "type": "Tillage",
    "name": "Chisel Plow, Front Dsk",
    "size1": 16.25,
    "unit1": "Ft",
    "default power unit": "200 HP MFWD Tractor",
    "purchase price 2020": 28500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 80,
    "default ASABE category": "Tandem disk harrow",
    "field speed (m/h)": 5,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 225,
    "size2": "",
    "unit2": ""
  },
  "Chisel Plow, Front Dsk; 21.3 Ft Fold": {
    "key": "Chisel Plow, Front Dsk; 21.3 Ft Fold",
    "type": "Tillage",
    "name": "Chisel Plow, Front Dsk",
    "size1": 21.25,
    "unit1": "Ft Fold",
    "default power unit": "310 HP 4WD Tractor",
    "purchase price 2020": 44500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 80,
    "default ASABE category": "Tandem disk harrow",
    "field speed (m/h)": 5,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 225,
    "size2": "",
    "unit2": ""
  },
  "Chisel Plow; 15 Ft": {
    "key": "Chisel Plow; 15 Ft",
    "type": "Tillage",
    "name": "Chisel Plow",
    "size1": 15,
    "unit1": "Ft",
    "default power unit": "130 HP MFWD Tractor",
    "purchase price 2020": 24000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 60,
    "default ASABE category": "Chisel plow",
    "field speed (m/h)": 5,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 225,
    "size2": "",
    "unit2": ""
  },
  "Chisel Plow; 23 Ft": {
    "key": "Chisel Plow; 23 Ft",
    "type": "Tillage",
    "name": "Chisel Plow",
    "size1": 23,
    "unit1": "Ft",
    "default power unit": "200 HP MFWD Tractor",
    "purchase price 2020": 43000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 60,
    "default ASABE category": "Chisel plow",
    "field speed (m/h)": 5,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 250,
    "size2": "",
    "unit2": ""
  },
  "Chisel Plow; 37 Ft": {
    "key": "Chisel Plow; 37 Ft",
    "type": "Tillage",
    "name": "Chisel Plow",
    "size1": 37,
    "unit1": "Ft",
    "default power unit": "310 HP 4WD Tractor",
    "purchase price 2020": 63000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 60,
    "default ASABE category": "Chisel plow",
    "field speed (m/h)": 5,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 370,
    "size2": "",
    "unit2": ""
  },
  "Chisel Plow; 57 Ft": {
    "key": "Chisel Plow; 57 Ft",
    "type": "Tillage",
    "name": "Chisel Plow",
    "size1": 57,
    "unit1": "Ft",
    "default power unit": "425 HP 4WD Tractor",
    "purchase price 2020": 105500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 60,
    "default ASABE category": "Chisel plow",
    "field speed (m/h)": 5,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 370,
    "size2": "",
    "unit2": ""
  },
  "Combine Belt Pickup Hd; 23 Ft": {
    "key": "Combine Belt Pickup Hd; 23 Ft",
    "type": "Harvest",
    "name": "Combine Belt Pickup Hd",
    "size1": 23,
    "unit1": "Ft",
    "default power unit": "275 HP Combine",
    "purchase price 2020": 44000,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 106.52173913043478,
    "default ASABE category": "Combine (self propelled)",
    "field speed (m/h)": 4,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 75,
    "size2": "",
    "unit2": ""
  },
  "Combine Chopping Corn Hd; 8 Row; 20 Ft": {
    "key": "Combine Chopping Corn Hd; 8 Row; 20 Ft",
    "type": "Harvest",
    "name": "Combine Chopping Corn Hd",
    "size1": 20,
    "unit1": "Ft",
    "size2": "8",
    "unit2": "Row",
    "default power unit": "275 HP Combine",
    "purchase price 2020": 88000,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Beet topper/stalk chopper",
    "field speed (m/h)": 4,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 160
  },
  "Combine Chopping Corn Hd; 12 Row; 22 Ft": {
    "key": "Combine Chopping Corn Hd; 12 Row; 22 Ft",
    "type": "Harvest",
    "name": "Combine Chopping Corn Hd",
    "size1": 22,
    "unit1": "Ft",
    "size2": "12",
    "unit2": "Row",
    "default power unit": "440 HP Combine",
    "purchase price 2020": 131500,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Beet topper/stalk chopper",
    "field speed (m/h)": 4,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 160
  },
  "Combine Chopping Corn Hd; 12 Row; 30 Ft": {
    "key": "Combine Chopping Corn Hd; 12 Row; 30 Ft",
    "type": "Harvest",
    "name": "Combine Chopping Corn Hd",
    "size1": 30,
    "unit1": "Ft",
    "size2": "12",
    "unit2": "Row",
    "default power unit": "440 HP Combine",
    "purchase price 2020": 133000,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Beet topper/stalk chopper",
    "field speed (m/h)": 4,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 160
  },
  "Combine Corn Hd; 6 Row; 15 Ft": {
    "key": "Combine Corn Hd; 6 Row; 15 Ft",
    "type": "Harvest",
    "name": "Combine Corn Hd",
    "size1": 15,
    "unit1": "Ft",
    "size2": "6",
    "unit2": "Row",
    "default power unit": "275 HP Combine",
    "purchase price 2020": 50000,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Combine (self propelled)",
    "field speed (m/h)": 4,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 120
  },
  "Combine Corn Hd; 8 Row; 20 Ft": {
    "key": "Combine Corn Hd; 8 Row; 20 Ft",
    "type": "Harvest",
    "name": "Combine Corn Hd",
    "size1": 20,
    "unit1": "Ft",
    "size2": "8",
    "unit2": "Row",
    "default power unit": "275 HP Combine",
    "purchase price 2020": 64500,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Combine (self propelled)",
    "field speed (m/h)": 4,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 160
  },
  "Combine Corn Hd; 12 Row; 22 Ft": {
    "key": "Combine Corn Hd; 12 Row; 22 Ft",
    "type": "Harvest",
    "name": "Combine Corn Hd",
    "size1": 22,
    "unit1": "Ft",
    "size2": "12",
    "unit2": "Row",
    "default power unit": "375 HP Combine",
    "purchase price 2020": 99500,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Combine (self propelled)",
    "field speed (m/h)": 4,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 160
  },
  "Combine Corn Hd; 12 Row; 30 Ft": {
    "key": "Combine Corn Hd; 12 Row; 30 Ft",
    "type": "Harvest",
    "name": "Combine Corn Hd",
    "size1": 30,
    "unit1": "Ft",
    "size2": "12",
    "unit2": "Row",
    "default power unit": "375 HP Combine",
    "purchase price 2020": 101000,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Combine (self propelled)",
    "field speed (m/h)": 4,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 160
  },
  "Combine Flex Platform; 20 Ft": {
    "key": "Combine Flex Platform; 20 Ft",
    "type": "Harvest",
    "name": "Combine Flex Platform",
    "size1": 20,
    "unit1": "Ft",
    "default power unit": "275 HP Combine",
    "purchase price 2020": 31000,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 199.99999999999997,
    "default ASABE category": "Combine (self propelled)",
    "field speed (m/h)": 3.5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 108,
    "size2": "",
    "unit2": ""
  },
  "Combine Flex Platform; 25 Ft": {
    "key": "Combine Flex Platform; 25 Ft",
    "type": "Harvest",
    "name": "Combine Flex Platform",
    "size1": 25,
    "unit1": "Ft",
    "default power unit": "375 HP Combine",
    "purchase price 2020": 35500,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Combine (self propelled)",
    "field speed (m/h)": 3.5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 108,
    "size2": "",
    "unit2": ""
  },
  "Combine Flex Platform; 30 Ft": {
    "key": "Combine Flex Platform; 30 Ft",
    "type": "Harvest",
    "name": "Combine Flex Platform",
    "size1": 30,
    "unit1": "Ft",
    "default power unit": "375 HP Combine",
    "purchase price 2020": 43000,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Combine (self propelled)",
    "field speed (m/h)": 3.5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 108,
    "size2": "",
    "unit2": ""
  },
  "Cover Crop Roller; 8 Ft": {
    "key": "Cover Crop Roller; 8 Ft",
    "type": "Termination",
    "name": "Cover Crop Roller",
    "size1": 8,
    "unit1": "Ft",
    "default power unit": "60 HP Tractor",
    "purchase price 2020": 6000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Field cultivators",
    "field speed (m/h)": 6,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 130,
    "size2": "",
    "unit2": ""
  },
  "Cover Crop Roller; 10.5 Ft": {
    "key": "Cover Crop Roller; 10.5 Ft",
    "type": "Termination",
    "name": "Cover Crop Roller",
    "size1": 10.5,
    "unit1": "Ft",
    "default power unit": "75 HP Tractor",
    "purchase price 2020": 6900,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Field cultivators",
    "field speed (m/h)": 6,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 150,
    "size2": "",
    "unit2": ""
  },
  "Cover Crop Roller; 15.5 Ft": {
    "key": "Cover Crop Roller; 15.5 Ft",
    "type": "Termination",
    "name": "Cover Crop Roller",
    "size1": 15.5,
    "unit1": "Ft",
    "default power unit": "105 HP MFWD Tractor",
    "purchase price 2020": 9900,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Field cultivators",
    "field speed (m/h)": 6,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 200,
    "size2": "",
    "unit2": ""
  },
  "Cover Crop Roller; 30 Ft Fold": {
    "key": "Cover Crop Roller; 30 Ft Fold",
    "type": "Termination",
    "name": "Cover Crop Roller",
    "size1": 30,
    "unit1": "Ft Fold",
    "default power unit": "160 HP MFWD Tractor",
    "purchase price 2020": 34800,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Field cultivators",
    "field speed (m/h)": 6,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 300,
    "size2": "",
    "unit2": ""
  },
  "Field Cultivator; 23 Ft": {
    "key": "Field Cultivator; 23 Ft",
    "type": "Tillage",
    "name": "Field Cultivator",
    "size1": 23,
    "unit1": "Ft",
    "default power unit": "160 HP MFWD Tractor",
    "purchase price 2020": 40500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Field cultivators",
    "field speed (m/h)": 7,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 200,
    "size2": "",
    "unit2": ""
  },
  "Field Cultivator; 47 Ft": {
    "key": "Field Cultivator; 47 Ft",
    "type": "Tillage",
    "name": "Field Cultivator",
    "size1": 47,
    "unit1": "Ft",
    "default power unit": "310 HP 4WD Tractor",
    "purchase price 2020": 79000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Field cultivators",
    "field speed (m/h)": 7,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 400,
    "size2": "",
    "unit2": ""
  },
  "Field Cultivator; 60 Ft": {
    "key": "Field Cultivator; 60 Ft",
    "type": "Tillage",
    "name": "Field Cultivator",
    "size1": 60,
    "unit1": "Ft",
    "default power unit": "425 HP 4WD Tractor",
    "purchase price 2020": 94000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Field cultivators",
    "field speed (m/h)": 7,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 400,
    "size2": "",
    "unit2": ""
  },
  "Forage Harvester, Pull-Type w/Corn Head; 3 Row; 7.5 Ft": {
    "key": "Forage Harvester, Pull-Type w/Corn Head; 3 Row; 7.5 Ft",
    "type": "Harvest",
    "name": "Forage Harvester, Pull-Type w/Corn Head",
    "size1": 7.5,
    "unit1": "Ft",
    "size2": "3",
    "unit2": "Row",
    "default power unit": "160 HP MFWD Tractor",
    "purchase price 2020": 76000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Forage harvester",
    "field speed (m/h)": 3.5,
    "field efficiency": 0.65,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 140
  },
  "Forage Harvester, Pull-Type w/Pickup Head; 12 Ft": {
    "key": "Forage Harvester, Pull-Type w/Pickup Head; 12 Ft",
    "type": "Harvest",
    "name": "Forage Harvester, Pull-Type w/Pickup Head",
    "size1": 12,
    "unit1": "Ft",
    "default power unit": "105 HP MFWD Tractor",
    "purchase price 2020": 67000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Forage harvester",
    "field speed (m/h)": 3.5,
    "field efficiency": 0.65,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 140,
    "size2": "",
    "unit2": ""
  },
  "Forage Harvester, Self-Prop Corn Head; 6 Row; 15 Ft": {
    "key": "Forage Harvester, Self-Prop Corn Head; 6 Row; 15 Ft",
    "type": "Harvest",
    "name": "Forage Harvester, Self-Prop Corn Head",
    "size1": 15,
    "unit1": "Ft",
    "size2": "6",
    "unit2": "Row",
    "default power unit": "625 HP SP Forage Harvester Base Unit",
    "purchase price 2020": 88500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Forage harvester (SP)",
    "field speed (m/h)": 4,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 300
  },
  "Forage Harvester, Self-Prop Corn Head; 8 Row; 20 Ft": {
    "key": "Forage Harvester, Self-Prop Corn Head; 8 Row; 20 Ft",
    "type": "Harvest",
    "name": "Forage Harvester, Self-Prop Corn Head",
    "size1": 20,
    "unit1": "Ft",
    "size2": "8",
    "unit2": "Row",
    "default power unit": "625 HP SP Forage Harvester Base Unit",
    "purchase price 2020": 116500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Forage harvester (SP)",
    "field speed (m/h)": 4,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 300
  },
  "Forage Harvester, Self-Prop Pickup Head (2X windrows); 24 Ft": {
    "key": "Forage Harvester, Self-Prop Pickup Head (2X windrows); 24 Ft",
    "type": "Harvest",
    "name": "Forage Harvester, Self-Prop Pickup Head (2X windrows)",
    "size1": 24,
    "unit1": "Ft",
    "default power unit": "625 HP SP Forage Harvester Base Unit",
    "purchase price 2020": 29000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Forage harvester (SP)",
    "field speed (m/h)": 4,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 300,
    "size2": "",
    "unit2": ""
  },
  "Forage Harvester, Self-Prop Pickup Head; 12 Ft": {
    "key": "Forage Harvester, Self-Prop Pickup Head; 12 Ft",
    "type": "Harvest",
    "name": "Forage Harvester, Self-Prop Pickup Head",
    "size1": 12,
    "unit1": "Ft",
    "default power unit": "400 HP SP Forage Harvester Base Unit",
    "purchase price 2020": 29000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Forage harvester (SP)",
    "field speed (m/h)": 4,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 300,
    "size2": "",
    "unit2": ""
  },
  "Grain Cart; 30 Ft": {
    "key": "Grain Cart; 30 Ft",
    "type": "Harvest",
    "name": "Grain Cart",
    "size1": 30,
    "unit1": "Ft",
    "default power unit": "225 HP MFWD Tractor",
    "purchase price 2020": 123000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Wagon",
    "field speed (m/h)": 3,
    "field efficiency": 0.63,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Unskilled",
    "shed (ft^2)": 0,
    "size2": "",
    "unit2": ""
  },
  "Grain Swather, Self-Propelled; 25 Ft": {
    "key": "Grain Swather, Self-Propelled; 25 Ft",
    "type": "Harvest",
    "name": "Grain Swather, Self-Propelled",
    "size1": 25,
    "unit1": "Ft",
    "default power unit": " None Tractor",
    "purchase price 2020": 204500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 80,
    "default ASABE category": "Windrower (SP)",
    "field speed (m/h)": 5,
    "field efficiency": 0.8,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 345,
    "size2": "",
    "unit2": ""
  },
  "Hay Baler PTO Twine; 12 Ft": {
    "key": "Hay Baler PTO Twine; 12 Ft",
    "type": "Harvest",
    "name": "Hay Baler PTO Twine",
    "size1": 12,
    "unit1": "Ft",
    "default power unit": "60 HP Tractor",
    "purchase price 2020": 34500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Rectangular baler",
    "field speed (m/h)": 4,
    "field efficiency": 0.75,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 184,
    "size2": "",
    "unit2": ""
  },
  "Hay Rake; 30 Ft": {
    "key": "Hay Rake; 30 Ft",
    "type": "Harvest",
    "name": "Hay Rake",
    "size1": 30,
    "unit1": "Ft",
    "default power unit": "40 HP Tractor",
    "purchase price 2020": 25000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 80,
    "default ASABE category": "Side delivery rake",
    "field speed (m/h)": 9,
    "field efficiency": 0.8,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 250,
    "size2": "",
    "unit2": ""
  },
  "Large Rectangular Baler; 3x3 ; 20 Ft": {
    "key": "Large Rectangular Baler; 3x3 ; 20 Ft",
    "type": "Harvest",
    "name": "Large Rectangular Baler",
    "size1": 20,
    "unit1": "Ft",
    "size2": "3x3",
    "default power unit": "130 HP MFWD Tractor",
    "purchase price 2020": 131500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 250,
    "default ASABE category": "Large rectangular baler",
    "field speed (m/h)": 6,
    "field efficiency": 0.8,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 250,
    "unit2": ""
  },
  "Large Rectangular Baler; 4x3 ; 20 Ft": {
    "key": "Large Rectangular Baler; 4x3 ; 20 Ft",
    "type": "Harvest",
    "name": "Large Rectangular Baler",
    "size1": 20,
    "unit1": "Ft",
    "size2": "4x3",
    "default power unit": "200 HP MFWD Tractor",
    "purchase price 2020": 159500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 250,
    "default ASABE category": "Large rectangular baler",
    "field speed (m/h)": 6,
    "field efficiency": 0.8,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 250,
    "unit2": ""
  },
  "Moldboard Plow; 6 Bottom; 9 Ft": {
    "key": "Moldboard Plow; 6 Bottom; 9 Ft",
    "type": "Tillage",
    "name": "Moldboard Plow",
    "size1": 9,
    "unit1": "Ft",
    "size2": "6",
    "unit2": "Bottom",
    "default power unit": "130 HP MFWD Tractor",
    "purchase price 2020": 37500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 120,
    "default ASABE category": "Moldboard plows",
    "field speed (m/h)": 4.5,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 132
  },
  "Moldboard Plow; 8 Bottom; 12 Ft": {
    "key": "Moldboard Plow; 8 Bottom; 12 Ft",
    "type": "Tillage",
    "name": "Moldboard Plow",
    "size1": 12,
    "unit1": "Ft",
    "size2": "8",
    "unit2": "Bottom",
    "default power unit": "200 HP MFWD Tractor",
    "purchase price 2020": 47500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 120,
    "default ASABE category": "Moldboard plows",
    "field speed (m/h)": 4.5,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 150
  },
  "No-Till Drill ; 15 Ft": {
    "key": "No-Till Drill ; 15 Ft",
    "type": "Planting",
    "name": "No-Till Drill ",
    "size1": 15,
    "unit1": "Ft",
    "default power unit": "130 HP MFWD Tractor",
    "purchase price 2020": 62500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 80,
    "default ASABE category": "Grain drill",
    "field speed (m/h)": 5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 160,
    "size2": "",
    "unit2": ""
  },
  "No-Till Drill; 20 Ft": {
    "key": "No-Till Drill; 20 Ft",
    "type": "Planting",
    "name": "No-Till Drill ",
    "size1": 20,
    "unit1": "Ft",
    "default power unit": "160 HP MFWD Tractor",
    "purchase price 2020": 72000,
    "list discount": 0.05,
    "expected life (years)": 12,
    "expected use (hr/yr)": 80,
    "default ASABE category": "Grain drill",
    "field speed (m/h)": 5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 185,
    "size2": "",
    "unit2": ""
  },
  "No-Till Drill; 25 Ft Fold": {
    "key": "No-Till Drill; 25 Ft Fold",
    "type": "Planting",
    "name": "No-Till Drill ",
    "size1": 25,
    "unit1": "Ft Fold",
    "default power unit": "200 HP MFWD Tractor",
    "purchase price 2020": 80000,
    "list discount": 0.05,
    "expected life (years)": 12,
    "expected use (hr/yr)": 80,
    "default ASABE category": "Grain drill",
    "field speed (m/h)": 5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 230,
    "size2": "",
    "unit2": ""
  },
  "No-Till Drill; 30 Ft Fold": {
    "key": "No-Till Drill; 30 Ft Fold",
    "type": "Planting",
    "name": "No-Till Drill ",
    "size1": 30,
    "unit1": "Ft Fold",
    "default power unit": "260 HP MFWD Tractor",
    "purchase price 2020": 92000,
    "list discount": 0.05,
    "expected life (years)": 12,
    "expected use (hr/yr)": 80,
    "default ASABE category": "Grain drill",
    "field speed (m/h)": 5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 250,
    "size2": "",
    "unit2": ""
  },
  "No-Till Drill; 40 Ft Fold": {
    "key": "No-Till Drill; 40 Ft Fold",
    "type": "Planting",
    "name": "No-Till Drill ",
    "size1": 30,
    "unit1": "Ft Fold",
    "default power unit": "310 HP 4WD Tractor",
    "purchase price 2020": 104000,
    "list discount": 0.05,
    "expected life (years)": 12,
    "expected use (hr/yr)": 80,
    "default ASABE category": "Grain drill",
    "field speed (m/h)": 5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 300,
    "size2": "",
    "unit2": ""
  },
  "Offset Disk; 12 Ft": {
    "key": "Offset Disk; 12 Ft",
    "type": "Tillage",
    "name": "Offset Disk",
    "size1": 12,
    "unit1": "Ft",
    "default power unit": "105 HP MFWD Tractor",
    "purchase price 2020": 27500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Heavy Duty disk harrow",
    "field speed (m/h)": 4.5,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 150,
    "size2": "",
    "unit2": ""
  },
  "Presswheel Drill; 16 Ft": {
    "key": "Presswheel Drill; 16 Ft",
    "type": "Planting",
    "name": "Presswheel Drill",
    "size1": 16,
    "unit1": "Ft",
    "default power unit": "105 HP MFWD Tractor",
    "purchase price 2020": 24500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 75,
    "default ASABE category": "Grain drill",
    "field speed (m/h)": 5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 150,
    "size2": "",
    "unit2": ""
  },
  "Presswheel Drill; 20 Ft": {
    "key": "Presswheel Drill; 20 Ft",
    "type": "Planting",
    "name": "Presswheel Drill",
    "size1": 20,
    "unit1": "Ft",
    "default power unit": "130 HP MFWD Tractor",
    "purchase price 2020": 29000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 75,
    "default ASABE category": "Grain drill",
    "field speed (m/h)": 5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 185,
    "size2": "",
    "unit2": ""
  },
  "Presswheel Drill; 25 Ft": {
    "key": "Presswheel Drill; 25 Ft",
    "type": "Planting",
    "name": "Presswheel Drill",
    "size1": 25,
    "unit1": "Ft",
    "default power unit": "130 HP MFWD Tractor",
    "purchase price 2020": 51000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 75,
    "default ASABE category": "Grain drill",
    "field speed (m/h)": 5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 230,
    "size2": "",
    "unit2": ""
  },
  "Presswheel Drill; 30 Ft": {
    "key": "Presswheel Drill; 30 Ft",
    "type": "Planting",
    "name": "Presswheel Drill",
    "size1": 30,
    "unit1": "Ft",
    "default power unit": "160 HP MFWD Tractor",
    "purchase price 2020": 63500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 80,
    "default ASABE category": "Grain drill",
    "field speed (m/h)": 5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 240,
    "size2": "",
    "unit2": ""
  },
  "Ripper/subsoiler; 12.5 Ft": {
    "key": "Ripper/subsoiler; 12.5 Ft",
    "type": "Tillage",
    "name": "V-Ripper",
    "size1": 10,
    "unit1": "Ft",
    "default power unit": "160 HP MFWD Tractor",
    "purchase price 2020": 16500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Chisel plow",
    "field speed (m/h)": 6,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 150,
    "size2": "",
    "unit2": ""
  },
  "Ripper/subsoiler; 17.5 Ft": {
    "key": "Ripper/subsoiler; 17.5 Ft",
    "type": "Tillage",
    "name": "V-Ripper",
    "size1": 17,
    "unit1": "Ft",
    "default power unit": "260 HP MFWD Tractor",
    "purchase price 2020": 22000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Chisel plow",
    "field speed (m/h)": 6,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 240,
    "size2": "",
    "unit2": ""
  },
  "Ripper/subsoiler; 22.5 Ft": {
    "key": "Ripper/subsoiler; 22.5 Ft",
    "type": "Tillage",
    "name": "V-Ripper",
    "size1": 18,
    "unit1": "Ft",
    "default power unit": "360 HP 4WD Tractor",
    "purchase price 2020": 27000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Chisel plow",
    "field speed (m/h)": 6,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 250,
    "size2": "",
    "unit2": ""
  },
  "Ripper/subsoiler; 27.5 Ft": {
    "key": "Ripper/subsoiler; 27.5 Ft",
    "type": "Tillage",
    "name": "V-Ripper",
    "size1": 22.5,
    "unit1": "Ft",
    "default power unit": "425 HP 4WD Tractor",
    "purchase price 2020": 31000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Chisel plow",
    "field speed (m/h)": 6,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 240,
    "size2": "",
    "unit2": ""
  },
  "Rotary Mower/Conditioner; 12 Ft": {
    "key": "Rotary Mower/Conditioner; 12 Ft",
    "type": "Harvest",
    "name": "Rotary Mower/Conditioner",
    "size1": 12,
    "unit1": "Ft",
    "default power unit": "75 HP Tractor",
    "purchase price 2020": 37500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 80,
    "default ASABE category": "Mower-conditioner (rotary)",
    "field speed (m/h)": 7.5,
    "field efficiency": 0.8,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.05,
    "labortype": "Unskilled",
    "shed (ft^2)": 100,
    "size2": "",
    "unit2": ""
  },
  "Round Baler w/Bale Wrap; 5x6 ; 20 Ft": {
    "key": "Round Baler w/Bale Wrap; 5x6 ; 20 Ft",
    "type": "Harvest",
    "name": "Round Baler w/Bale Wrap",
    "size1": 20,
    "unit1": "Ft",
    "size2": "5x6",
    "default power unit": "75 HP Tractor",
    "purchase price 2020": 84000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Large round baler",
    "field speed (m/h)": 6,
    "field efficiency": 0.65,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 60,
    "unit2": ""
  },
  "Round Baler; 4x5 ; 20 Ft": {
    "key": "Round Baler; 4x5 ; 20 Ft",
    "type": "Harvest",
    "name": "Round Baler",
    "size1": 20,
    "unit1": "Ft",
    "size2": "4x5",
    "default power unit": "75 HP Tractor",
    "purchase price 2020": 55000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Large round baler",
    "field speed (m/h)": 6,
    "field efficiency": 0.65,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 60,
    "unit2": ""
  },
  "Round Baler; 5x6 ; 20 Ft": {
    "key": "Round Baler; 5x6 ; 20 Ft",
    "type": "Harvest",
    "name": "Round Baler",
    "size1": 20,
    "unit1": "Ft",
    "size2": "5x6",
    "default power unit": "105 HP MFWD Tractor",
    "purchase price 2020": 64000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Large round baler",
    "field speed (m/h)": 6,
    "field efficiency": 0.65,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 60,
    "unit2": ""
  },
  "Row Crop Planter; 6 Row; 15 Ft": {
    "key": "Row Crop Planter; 6 Row; 15 Ft",
    "type": "Planting",
    "name": "Row Crop Planter",
    "size1": 15,
    "unit1": "Ft",
    "size2": "6",
    "unit2": "Row",
    "default power unit": "75 HP Tractor",
    "purchase price 2020": 37000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 70,
    "default ASABE category": "Row crop planter",
    "field speed (m/h)": 5.5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.16,
    "labortype": "Skilled",
    "shed (ft^2)": 200
  },
  "Row Crop Planter; 8 Row; 20 Ft": {
    "key": "Row Crop Planter; 8 Row; 20 Ft",
    "type": "Planting",
    "name": "Row Crop Planter",
    "size1": 20,
    "unit1": "Ft",
    "size2": "8",
    "unit2": "Row",
    "default power unit": "105 HP MFWD Tractor",
    "purchase price 2020": 46000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 70,
    "default ASABE category": "Row crop planter",
    "field speed (m/h)": 5.5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.16,
    "labortype": "Skilled",
    "shed (ft^2)": 200
  },
  "Row Crop Planter; 12 Row; 30 Ft": {
    "key": "Row Crop Planter; 12 Row; 30 Ft",
    "type": "Planting",
    "name": "Row Crop Planter",
    "size1": 30,
    "unit1": "Ft",
    "size2": "12",
    "unit2": "Row",
    "default power unit": "130 HP MFWD Tractor",
    "purchase price 2020": 109500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 70.00000000000001,
    "default ASABE category": "Row crop planter",
    "field speed (m/h)": 5.5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.16,
    "labortype": "Skilled",
    "shed (ft^2)": 300
  },
  "Row Crop Planter; 16 Row; 40 Ft": {
    "key": "Row Crop Planter; 16 Row; 40 Ft",
    "type": "Planting",
    "name": "Row Crop Planter",
    "size1": 40,
    "unit1": "Ft",
    "size2": "16",
    "unit2": "Row",
    "default power unit": "200 HP MFWD Tractor",
    "purchase price 2020": 166500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 70,
    "default ASABE category": "Row crop planter",
    "field speed (m/h)": 5.5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.16,
    "labortype": "Skilled",
    "shed (ft^2)": 300
  },
  "Row Crop Planter; 24 Row; 60 Ft": {
    "key": "Row Crop Planter; 24 Row; 60 Ft",
    "type": "Planting",
    "name": "Row Crop Planter",
    "size1": 60,
    "unit1": "Ft",
    "size2": "24",
    "unit2": "Row",
    "default power unit": "310 HP 4WD Tractor",
    "purchase price 2020": 254500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 70,
    "default ASABE category": "Row crop planter",
    "field speed (m/h)": 5.5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.16,
    "labortype": "Skilled",
    "shed (ft^2)": 300
  },
  "Row Cultivator; 12 Row; 30 Ft": {
    "key": "Row Cultivator; 12 Row; 30 Ft",
    "type": "CropMaint",
    "name": "Row Cultivator",
    "size1": 30,
    "unit1": "Ft",
    "size2": "12",
    "unit2": "Row",
    "default power unit": "160 HP MFWD Tractor",
    "purchase price 2020": 44500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Row crop cultivator",
    "field speed (m/h)": 5,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.04,
    "labortype": "Unskilled",
    "shed (ft^2)": 140
  },
  "Stalk Shredder; 20 Ft": {
    "key": "Stalk Shredder; 20 Ft",
    "type": "CropMaint",
    "name": "Stalk Shredder",
    "size1": 20,
    "unit1": "Ft",
    "default power unit": "130 HP MFWD Tractor",
    "purchase price 2020": 31000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Beet topper/stalk chopper",
    "field speed (m/h)": 4,
    "field efficiency": 0.8,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.1,
    "labortype": "Unskilled",
    "shed (ft^2)": 231,
    "size2": "",
    "unit2": ""
  },
  "Tandem Disk; 21 Ft Fold": {
    "key": "Tandem Disk; 21 Ft Fold",
    "type": "Tillage",
    "name": "Tandem Disk",
    "size1": 21,
    "unit1": "Ft Fold",
    "default power unit": "160 HP MFWD Tractor",
    "purchase price 2020": 68000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Chisel plow",
    "field speed (m/h)": 6,
    "field efficiency": 0.8,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 260,
    "size2": "",
    "unit2": ""
  },
  "Tandem Disk; 30 Ft Fold": {
    "key": "Tandem Disk; 30 Ft Fold",
    "type": "Tillage",
    "name": "Tandem Disk",
    "size1": 30,
    "unit1": "Ft Fold",
    "default power unit": "260 HP MFWD Tractor",
    "purchase price 2020": 93500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Chisel plow",
    "field speed (m/h)": 6,
    "field efficiency": 0.8,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 280,
    "size2": "",
    "unit2": ""
  },
  "Vertical Tillage; 15 Ft": {
    "key": "Vertical Tillage; 15 Ft",
    "type": "Tillage",
    "name": "Vertical Tillage",
    "size1": 15,
    "unit1": "Ft",
    "default power unit": "160 HP MFWD Tractor",
    "purchase price 2020": 61000,
    "list discount": 0,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Tandem disk harrow",
    "field speed (m/h)": 9,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.05,
    "labortype": "Unskilled",
    "shed (ft^2)": 200,
    "size2": "",
    "unit2": ""
  },
  "Vertical Tillage; 20 Ft Fold": {
    "key": "Vertical Tillage; 20 Ft Fold",
    "type": "Tillage",
    "name": "Vertical Tillage",
    "size1": 20,
    "unit1": "Ft Fold",
    "default power unit": "200 HP MFWD Tractor",
    "purchase price 2020": 90000,
    "list discount": 0,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Tandem disk harrow",
    "field speed (m/h)": 9,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.05,
    "labortype": "Unskilled",
    "shed (ft^2)": 180,
    "size2": "",
    "unit2": ""
  },
  "Vertical Tillage; 25 Ft Fold": {
    "key": "Vertical Tillage; 25 Ft Fold",
    "type": "Tillage",
    "name": "Vertical Tillage",
    "size1": 25,
    "unit1": "Ft Fold",
    "default power unit": "260 HP MFWD Tractor",
    "purchase price 2020": 115000,
    "list discount": 0.05,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Tandem disk harrow",
    "field speed (m/h)": 9,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.05,
    "labortype": "Unskilled",
    "shed (ft^2)": 200,
    "size2": "",
    "unit2": ""
  },
  "Vertical Tillage; 30 Ft Fold": {
    "key": "Vertical Tillage; 30 Ft Fold",
    "type": "Tillage",
    "name": "Vertical Tillage",
    "size1": 30,
    "unit1": "Ft Fold",
    "default power unit": "310 HP 4WD Tractor",
    "purchase price 2020": 132500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Tandem disk harrow",
    "field speed (m/h)": 9,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.05,
    "labortype": "Unskilled",
    "shed (ft^2)": 225,
    "size2": "",
    "unit2": ""
  },
  "Vertical Tillage; 40 Ft Fold": {
    "key": "Vertical Tillage; 40 Ft Fold",
    "type": "Tillage",
    "name": "Vertical Tillage",
    "size1": 40,
    "unit1": "Ft Fold",
    "default power unit": "425 HP 4WD Tractor",
    "purchase price 2020": 161000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Tandem disk harrow",
    "field speed (m/h)": 9,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.05,
    "labortype": "Unskilled",
    "shed (ft^2)": 225,
    "size2": "",
    "unit2": ""
  }
};

const ATpower = {
  "40 HP Tractor": {
    "key": "40 HP Tractor",
    "Description": "HP Tractor",
    "HP": 40,
    "purchase price 2020": 26000,
    "list discount": 0,
    "expected life (years)": 12,
    "expected use (hr/yr)": 400,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 92,
    "default ASABE category": "Two wheel drive tractors, under 80 HP"
  },
  "60 HP Tractor": {
    "key": "60 HP Tractor",
    "Description": "HP Tractor",
    "HP": 60,
    "purchase price 2020": 33000,
    "list discount": 0,
    "expected life (years)": 12,
    "expected use (hr/yr)": 400,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 104,
    "default ASABE category": "Two wheel drive tractors, under 80 HP"
  },
  "75 HP Tractor": {
    "key": "75 HP Tractor",
    "Description": "HP Tractor",
    "HP": 75,
    "purchase price 2020": 54000,
    "list discount": 0.05,
    "expected life (years)": 12,
    "expected use (hr/yr)": 400,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 115,
    "default ASABE category": "Two wheel drive tractors, under 80 HP"
  },
  "105 HP MFWD Tractor": {
    "key": "105 HP MFWD Tractor",
    "Description": "HP MFWD Tractor",
    "HP": 105,
    "purchase price 2020": 145000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 450,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 127,
    "default ASABE category": "Mech. front wheel drive tractors"
  },
  "130 HP MFWD Tractor": {
    "key": "130 HP MFWD Tractor",
    "Description": "HP MFWD Tractor",
    "HP": 130,
    "purchase price 2020": 176000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 450,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 130,
    "default ASABE category": "Mech. front wheel drive tractors"
  },
  "130 Self Propelled": {
    "key": "130 Self Propelled",
    "Description": "130 Self Propelled",
    "HP": 130,
    "expected use (hr/yr)": 200,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "default ASABE category": "None",
    "purchase price 2020": "",
    "list discount": "",
    "expected life (years)": "",
    "shed (ft^2)": ""
  },
  "160 HP MFWD Tractor": {
    "key": "160 HP MFWD Tractor",
    "Description": "HP MFWD Tractor",
    "HP": 160,
    "purchase price 2020": 215000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 500,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 200,
    "default ASABE category": "Mech. front wheel drive tractors"
  },
  "200 HP MFWD Tractor": {
    "key": "200 HP MFWD Tractor",
    "Description": "HP MFWD Tractor",
    "HP": 200,
    "purchase price 2020": 277000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 500,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 230,
    "default ASABE category": "Mech. front wheel drive tractors"
  },
  "225 HP MFWD Tractor": {
    "key": "225 HP MFWD Tractor",
    "Description": "HP MFWD Tractor",
    "HP": 225,
    "purchase price 2020": 301000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 400,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 230,
    "default ASABE category": "Mech. front wheel drive tractors"
  },
  "260 HP MFWD Tractor": {
    "key": "260 HP MFWD Tractor",
    "Description": "HP MFWD Tractor",
    "HP": 260,
    "purchase price 2020": 345000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 400,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 230,
    "default ASABE category": "Four wheel drive tractors & crawlers"
  },
  "260 HP Tracked Tractor": {
    "key": "260 HP Tracked Tractor",
    "Description": "HP Tracked Tractor",
    "HP": 260,
    "purchase price 2020": 342000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 400,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 250,
    "default ASABE category": "Four wheel drive tractors & crawlers"
  },
  "275 HP Combine": {
    "key": "275 HP Combine",
    "Description": "HP Combine",
    "HP": 275,
    "purchase price 2020": 362000,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 400,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 400,
    "default ASABE category": "Combine (self propelled)"
  },
  "310 HP 4WD Tractor": {
    "key": "310 HP 4WD Tractor",
    "Description": "HP 4WD Tractor",
    "HP": 310,
    "purchase price 2020": 420000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 400,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 250,
    "default ASABE category": "Four wheel drive tractors & crawlers"
  },
  "350 HP Tracked Tractor": {
    "key": "350 HP Tracked Tractor",
    "Description": "HP Tracked Tractor",
    "HP": 350,
    "purchase price 2020": 460000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 400,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 250,
    "default ASABE category": "Four wheel drive tractors & crawlers"
  },
  "360 HP 4WD Tractor": {
    "key": "360 HP 4WD Tractor",
    "Description": "HP 4WD Tractor",
    "HP": 360,
    "purchase price 2020": 379000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 400,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 250,
    "default ASABE category": "Four wheel drive tractors & crawlers"
  },
  "375 HP Combine": {
    "key": "375 HP Combine",
    "Description": "HP Combine",
    "HP": 375,
    "purchase price 2020": 418000,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 400,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 500,
    "default ASABE category": "Combine (self propelled)"
  },
  "400 HP SP Forage Harvester Base Unit": {
    "key": "400 HP SP Forage Harvester Base Unit",
    "Description": "HP SP Forage Harvester Base Unit",
    "HP": 400,
    "purchase price 2020": 397000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 350,
    "fuel use (gal/PTO hp/hr)": 0.024,
    "shed (ft^2)": 500,
    "default ASABE category": "Forage harvester (SP)"
  },
  "425 HP 4WD Tractor": {
    "key": "425 HP 4WD Tractor",
    "Description": "HP 4WD Tractor",
    "HP": 425,
    "purchase price 2020": 452000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 400,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 250,
    "default ASABE category": "Four wheel drive tractors & crawlers"
  },
  "440 HP Combine": {
    "key": "440 HP Combine",
    "Description": "HP Combine",
    "HP": 440,
    "purchase price 2020": 443000,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 400,
    "fuel use (gal/PTO hp/hr)": 0.038305882,
    "shed (ft^2)": 500,
    "default ASABE category": "Combine (self propelled)"
  },
  "550 HP 4WD Tractor": {
    "key": "550 HP 4WD Tractor",
    "Description": "HP 4WD Tractor",
    "HP": 550,
    "purchase price 2020": 544000,
    "list discount": 0.05,
    "expected life (years)": 12,
    "expected use (hr/yr)": 400,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 300,
    "default ASABE category": "Four wheel drive tractors & crawlers"
  },
  "550 HP Tracked Tractor": {
    "key": "550 HP Tracked Tractor",
    "Description": "HP Tracked Tractor",
    "HP": 550,
    "purchase price 2020": 677000,
    "list discount": 0.05,
    "expected life (years)": 12,
    "expected use (hr/yr)": 400,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 250,
    "default ASABE category": "Four wheel drive tractors & crawlers"
  },
  "625 HP SP Forage Harvester Base Unit": {
    "key": "625 HP SP Forage Harvester Base Unit",
    "Description": "HP SP Forage Harvester Base Unit",
    "HP": 625,
    "purchase price 2020": 559000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 350,
    "fuel use (gal/PTO hp/hr)": 0.024,
    "shed (ft^2)": 500,
    "default ASABE category": "Forage harvester (SP)"
  }
};

const ATseedList = {
  "Alfalfa": {
    "key": "Alfalfa",
    "seedingRate": 15,
    "price": 4.29,
    "type": "Legume",
    "Notes": "Updated 4-17-23 Prices are average of 6 sources internet price sheet. Seeding rate is average of covercrop council pubs. Data in CoverCrop rates and prices.xlsx.",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Barley, Spring": {
    "key": "Barley, Spring",
    "seedingRate": 80,
    "price": 0.5,
    "type": "Grass",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Barley, Winter": {
    "key": "Barley, Winter",
    "seedingRate": 100,
    "price": 0.78,
    "type": "Grass",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Brassica, Forage": {
    "key": "Brassica, Forage",
    "seedingRate": 4,
    "price": 4.32,
    "type": "Brassica",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Buckwheat": {
    "key": "Buckwheat",
    "seedingRate": 70,
    "price": 1.74,
    "type": "Broadleaf",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Cereal Rye, Spring": {
    "key": "Cereal Rye, Spring",
    "seedingRate": 75,
    "price": 0.6,
    "NCredit": 0,
    "erosion": true,
    "type": "Grass",
    "Notes": "Updated 4-17-23",
    "legume": ""
  },
  "Cereal Rye, Winter": {
    "key": "Cereal Rye, Winter",
    "seedingRate": 100,
    "price": 0.6,
    "NCredit": 0,
    "erosion": true,
    "type": "Grass",
    "Notes": "Updated 4-17-23",
    "legume": ""
  },
  "Clover, Alsike": {
    "key": "Clover, Alsike",
    "seedingRate": 6,
    "price": 3,
    "type": "Legume",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Clover, Balansa": {
    "key": "Clover, Balansa",
    "seedingRate": 6,
    "price": 3.07,
    "type": "Legume",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Clover, Berseem": {
    "key": "Clover, Berseem",
    "seedingRate": 14,
    "price": 3.01,
    "type": "Legume",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Clover, Crimson": {
    "key": "Clover, Crimson",
    "seedingRate": 17,
    "price": 2.34,
    "legume": true,
    "NCredit": 30,
    "type": "Legume",
    "Notes": "Updated 4-17-23",
    "erosion": ""
  },
  "Clover, Red": {
    "key": "Clover, Red",
    "seedingRate": 10,
    "price": 3.25,
    "legume": true,
    "NCredit": 35,
    "type": "Legume",
    "Notes": "Updated 4-17-23",
    "erosion": ""
  },
  "Clover, White": {
    "key": "Clover, White",
    "seedingRate": 8,
    "price": 4.02,
    "legume": true,
    "NCredit": 30,
    "type": "Legume",
    "Notes": "Updated 4-17-23",
    "erosion": ""
  },
  "Cowpea": {
    "key": "Cowpea",
    "seedingRate": 60,
    "price": 1.22,
    "type": "Legume",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Millet, Japanese": {
    "key": "Millet, Japanese",
    "seedingRate": 20,
    "price": 1.32,
    "type": "Grass",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Millet, Pearl": {
    "key": "Millet, Pearl",
    "seedingRate": 15,
    "price": 1.88,
    "type": "Grass",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Mustard": {
    "key": "Mustard",
    "seedingRate": 10,
    "price": 3.26,
    "type": "Brassica",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Oats": {
    "key": "Oats",
    "seedingRate": 90,
    "price": 0.66,
    "NCredit": 0,
    "erosion": true,
    "type": "Grass",
    "Notes": "Updated 4-17-23",
    "legume": ""
  },
  "Oats, Black": {
    "key": "Oats, Black",
    "seedingRate": 32,
    "price": 0.51,
    "NCredit": 0,
    "erosion": true,
    "type": "Grass",
    "Notes": "Updated 4-17-23",
    "legume": ""
  },
  "Oats, Spring": {
    "key": "Oats, Spring",
    "seedingRate": 90,
    "price": 0.8,
    "NCredit": 0,
    "erosion": true,
    "type": "Grass",
    "Notes": "Updated 4-17-23",
    "legume": ""
  },
  "Pea, Spring": {
    "key": "Pea, Spring",
    "seedingRate": 100,
    "price": 0.83,
    "type": "Legume",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Pea, Winter": {
    "key": "Pea, Winter",
    "seedingRate": 65,
    "price": 0.82,
    "type": "Legume",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Phacelia": {
    "key": "Phacelia",
    "seedingRate": 8,
    "price": 7.35,
    "type": "Broadleaf",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Radish, Forage": {
    "key": "Radish, Forage",
    "seedingRate": 10,
    "price": 3,
    "type": "Brassica",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Radish, Oilseed": {
    "key": "Radish, Oilseed",
    "seedingRate": 6,
    "price": 1.8,
    "NCredit": 0,
    "type": "Brassica",
    "Notes": "Updated 4-17-23",
    "erosion": "",
    "legume": ""
  },
  "Rape, Oilseed, Spring": {
    "key": "Rape, Oilseed, Spring",
    "seedingRate": 6,
    "price": 1.8,
    "type": "Brassica",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Rape, Oilseed, Winter": {
    "key": "Rape, Oilseed, Winter",
    "seedingRate": 6,
    "price": 1.8,
    "type": "Brassica",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Rapeseed, Forage": {
    "key": "Rapeseed, Forage",
    "seedingRate": 10,
    "price": 1.2,
    "type": "Brassica",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Ryegrass, Annual": {
    "key": "Ryegrass, Annual",
    "seedingRate": 20,
    "price": 1.13,
    "NCredit": 0,
    "erosion": true,
    "type": "Grass",
    "Notes": "Updated 4-17-23",
    "legume": ""
  },
  "Ryegrass, Perennial": {
    "key": "Ryegrass, Perennial",
    "seedingRate": 20,
    "price": 2.91,
    "NCredit": 0,
    "erosion": true,
    "type": "Grass",
    "Notes": "Updated 4-17-23",
    "legume": ""
  },
  "Sorghum": {
    "key": "Sorghum",
    "seedingRate": 30,
    "price": 1.45,
    "type": "Grass",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Sorghum-sudangrass": {
    "key": "Sorghum-sudangrass",
    "seedingRate": 40,
    "price": 1.32,
    "type": "Grass",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Soybeans": {
    "key": "Soybeans",
    "seedingRate": 50,
    "price": 1.28,
    "type": "Legume",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Sudangrass": {
    "key": "Sudangrass",
    "seedingRate": 30,
    "price": 1.39,
    "type": "Grass",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Sunflower": {
    "key": "Sunflower",
    "seedingRate": 5,
    "price": 1.51,
    "type": "Broadleaf",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Sunn Hemp": {
    "key": "Sunn Hemp",
    "seedingRate": 30,
    "price": 1.89,
    "type": "Legume",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Sweetclover, Yellow": {
    "key": "Sweetclover, Yellow",
    "seedingRate": 15,
    "price": 3.25,
    "type": "Legume",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Teff": {
    "key": "Teff",
    "seedingRate": 8,
    "price": 2.87,
    "type": "Grass",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Triticale, Spring": {
    "key": "Triticale, Spring",
    "seedingRate": 90,
    "price": 0.55,
    "type": "Grass",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Triticale, Winter": {
    "key": "Triticale, Winter",
    "seedingRate": 110,
    "price": 0.55,
    "type": "Grass",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Turnip, Forage": {
    "key": "Turnip, Forage",
    "seedingRate": 8,
    "price": 2.43,
    "NCredit": 0,
    "type": "Brassica",
    "Notes": "Updated 4-17-23",
    "erosion": "",
    "legume": ""
  },
  "Turnip, Purple Top": {
    "key": "Turnip, Purple Top",
    "seedingRate": 10,
    "price": 1.9,
    "NCredit": 0,
    "type": "Brassica",
    "Notes": "Updated 4-17-23",
    "erosion": "",
    "legume": ""
  },
  "Vetch, Hairy": {
    "key": "Vetch, Hairy",
    "seedingRate": 20,
    "price": 2.43,
    "type": "Legume",
    "Notes": "Updated 4-17-23",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Wheat, Spring": {
    "key": "Wheat, Spring",
    "seedingRate": 120,
    "price": 0.5,
    "NCredit": 0,
    "erosion": true,
    "type": "Grass",
    "Notes": "Updated 4-17-23",
    "legume": ""
  },
  "Wheat, Winter": {
    "key": "Wheat, Winter",
    "seedingRate": 100,
    "price": 0.42,
    "NCredit": 0,
    "erosion": true,
    "type": "Grass",
    "Notes": "Updated 4-17-23",
    "legume": ""
  }
};

const ATstateRegions = {
  "ALABAMA": {
    "key": "ALABAMA",
    "ccRegion": "southern",
    "USDARegion": "South"
  },
  "ALASKA": {
    "key": "ALASKA",
    "USDARegion": "None",
    "ccRegion": ""
  },
  "ARIZONA": {
    "key": "ARIZONA",
    "ccRegion": "western",
    "USDARegion": "West"
  },
  "ARKANSAS": {
    "key": "ARKANSAS",
    "ccRegion": "southern",
    "USDARegion": "South"
  },
  "CALIFORNIA": {
    "key": "CALIFORNIA",
    "ccRegion": "western",
    "USDARegion": "West"
  },
  "COLORADO": {
    "key": "COLORADO",
    "ccRegion": "western",
    "USDARegion": "West"
  },
  "CONNECTICUT": {
    "key": "CONNECTICUT",
    "ccRegion": "northeast",
    "USDARegion": "Atlantic"
  },
  "DELAWARE": {
    "key": "DELAWARE",
    "ccRegion": "northeast",
    "USDARegion": "Atlantic"
  },
  "DISTRICT OF COLUMBIA": {
    "key": "DISTRICT OF COLUMBIA",
    "ccRegion": "northeast",
    "USDARegion": "Atlantic"
  },
  "FLORIDA": {
    "key": "FLORIDA",
    "ccRegion": "southern",
    "USDARegion": "South"
  },
  "GEORGIA": {
    "key": "GEORGIA",
    "ccRegion": "southern",
    "USDARegion": "South"
  },
  "HAWAII": {
    "key": "HAWAII",
    "USDARegion": "None",
    "ccRegion": ""
  },
  "IDAHO": {
    "key": "IDAHO",
    "ccRegion": "western",
    "USDARegion": "West"
  },
  "ILLINOIS": {
    "key": "ILLINOIS",
    "ccRegion": "midwest",
    "USDARegion": "Midwest"
  },
  "INDIANA": {
    "key": "INDIANA",
    "ccRegion": "midwest",
    "USDARegion": "Midwest"
  },
  "IOWA": {
    "key": "IOWA",
    "ccRegion": "midwest",
    "USDARegion": "Midwest"
  },
  "KANSAS": {
    "key": "KANSAS",
    "ccRegion": "western",
    "USDARegion": "Plains"
  },
  "KENTUCKY": {
    "key": "KENTUCKY",
    "ccRegion": "midwest",
    "USDARegion": "Atlantic"
  },
  "LOUISIANA": {
    "key": "LOUISIANA",
    "ccRegion": "southern",
    "USDARegion": "South"
  },
  "MAINE": {
    "key": "MAINE",
    "ccRegion": "northeast",
    "USDARegion": "Atlantic"
  },
  "MARYLAND": {
    "key": "MARYLAND",
    "ccRegion": "northeast",
    "USDARegion": "Atlantic"
  },
  "MASSACHUSETTS": {
    "key": "MASSACHUSETTS",
    "ccRegion": "northeast",
    "USDARegion": "Atlantic"
  },
  "MICHIGAN": {
    "key": "MICHIGAN",
    "ccRegion": "midwest",
    "USDARegion": "Midwest"
  },
  "MINNESOTA": {
    "key": "MINNESOTA",
    "ccRegion": "midwest",
    "USDARegion": "Midwest"
  },
  "MISSISSIPPI": {
    "key": "MISSISSIPPI",
    "ccRegion": "southern",
    "USDARegion": "South"
  },
  "MISSOURI": {
    "key": "MISSOURI",
    "ccRegion": "midwest",
    "USDARegion": "Midwest"
  },
  "MONTANA": {
    "key": "MONTANA",
    "ccRegion": "western",
    "USDARegion": "West"
  },
  "NEBRASKA": {
    "key": "NEBRASKA",
    "ccRegion": "western",
    "USDARegion": "Plains"
  },
  "NEVADA": {
    "key": "NEVADA",
    "ccRegion": "western",
    "USDARegion": "West"
  },
  "NEW HAMPSHIRE": {
    "key": "NEW HAMPSHIRE",
    "ccRegion": "northeast",
    "USDARegion": "Atlantic"
  },
  "NEW JERSEY": {
    "key": "NEW JERSEY",
    "ccRegion": "northeast",
    "USDARegion": "Atlantic"
  },
  "NEW MEXICO": {
    "key": "NEW MEXICO",
    "ccRegion": "western",
    "USDARegion": "West"
  },
  "NEW YORK": {
    "key": "NEW YORK",
    "ccRegion": "northeast",
    "USDARegion": "Atlantic"
  },
  "NORTH CAROLINA": {
    "key": "NORTH CAROLINA",
    "ccRegion": "southern",
    "USDARegion": "Atlantic"
  },
  "NORTH DAKOTA": {
    "key": "NORTH DAKOTA",
    "ccRegion": "western",
    "USDARegion": "Plains"
  },
  "OHIO": {
    "key": "OHIO",
    "ccRegion": "midwest",
    "USDARegion": "Midwest"
  },
  "OKLAHOMA": {
    "key": "OKLAHOMA",
    "ccRegion": "southern",
    "USDARegion": "Plains"
  },
  "OREGON": {
    "key": "OREGON",
    "ccRegion": "western",
    "USDARegion": "West"
  },
  "PENNSYLVANIA": {
    "key": "PENNSYLVANIA",
    "ccRegion": "northeast",
    "USDARegion": "Atlantic"
  },
  "RHODE ISLAND": {
    "key": "RHODE ISLAND",
    "ccRegion": "northeast",
    "USDARegion": "Atlantic"
  },
  "SOUTH CAROLINA": {
    "key": "SOUTH CAROLINA",
    "ccRegion": "southern",
    "USDARegion": "South"
  },
  "SOUTH DAKOTA": {
    "key": "SOUTH DAKOTA",
    "ccRegion": "western",
    "USDARegion": "Plains"
  },
  "TENNESSEE": {
    "key": "TENNESSEE",
    "ccRegion": "southern",
    "USDARegion": "Atlantic"
  },
  "TEXAS": {
    "key": "TEXAS",
    "ccRegion": "southern",
    "USDARegion": "Plains"
  },
  "UTAH": {
    "key": "UTAH",
    "ccRegion": "western",
    "USDARegion": "West"
  },
  "VERMONT": {
    "key": "VERMONT",
    "ccRegion": "northeast",
    "USDARegion": "Atlantic"
  },
  "VIRGINIA": {
    "key": "VIRGINIA",
    "ccRegion": "southern",
    "USDARegion": "Atlantic"
  },
  "WASHINGTON": {
    "key": "WASHINGTON",
    "ccRegion": "western",
    "USDARegion": "West"
  },
  "WEST VIRGINIA": {
    "key": "WEST VIRGINIA",
    "ccRegion": "northeast",
    "USDARegion": "Atlantic"
  },
  "WISCONSIN": {
    "key": "WISCONSIN",
    "ccRegion": "midwest",
    "USDARegion": "Midwest"
  },
  "WYOMING": {
    "key": "WYOMING",
    "ccRegion": "western",
    "USDARegion": "West"
  }
};

const ATcommodities = {
  "Corn": {
    "key": "Corn",
    "price": 5.91,
    "one year": 0.005200000000000001,
    "three year": 0.0176,
    "five year": 0.03,
    "Notes": "Price is 2023 RMA springtime price; % change is from SARE publication by Myers.",
    "order": 1,
    "yield": "22"
  },
  "Soybeans": {
    "key": "Soybeans",
    "price": 13.76,
    "one year": 0.0212,
    "three year": 0.0354,
    "five year": 0.0496,
    "Notes": "Price is 2023 RMA springtime price; % change is from SARE publication by Myers.",
    "order": 2,
    "yield": "33"
  },
  "Wheat": {
    "key": "Wheat",
    "price": 8.77,
    "Notes": "Price is 2022 RMA fall price",
    "order": 3,
    "one year": "",
    "three year": "",
    "five year": "",
    "yield": ""
  },
  "Grain Sorghum (milo)": {
    "key": "Grain Sorghum (milo)",
    "price": 5.84,
    "Notes": "Price is 2023 RMA springtime price",
    "order": 4,
    "one year": "",
    "three year": "",
    "five year": "",
    "yield": ""
  },
  "Cotton": {
    "key": "Cotton",
    "price": 0.85,
    "Notes": "Price is 2023 RMA springtime price for SE US",
    "order": 5,
    "one year": "",
    "three year": "",
    "five year": "",
    "yield": ""
  },
  "Rice": {
    "key": "Rice",
    "price": 0.255,
    "Notes": "Price is 2023RMA springtime price for SE US short/med grain rice",
    "order": 6,
    "one year": "",
    "three year": "",
    "five year": "",
    "yield": ""
  },
  "Sunflower": {
    "key": "Sunflower",
    "price": 0.305,
    "Notes": "Price is 2023 RMA springtime price",
    "order": 7,
    "one year": "",
    "three year": "",
    "five year": "",
    "yield": ""
  },
  "Canola": {
    "key": "Canola",
    "price": 0.305,
    "Notes": "Price is 2023 RMA springtime price",
    "order": 8,
    "one year": "",
    "three year": "",
    "five year": "",
    "yield": ""
  }
};

const ATeqip = {
  "AL": {
    "key": "AL",
    "basic": 52.36,
    "multiple": 64.02
  },
  "AR": {
    "key": "AR",
    "basic": 40.43,
    "multiple": 49.76
  },
  "CT": {
    "key": "CT",
    "basic": 52.44,
    "multiple": 64.1
  },
  "DC": {
    "key": "DC",
    "basic": 35.92,
    "multiple": 47.45
  },
  "DE": {
    "key": "DE",
    "basic": 56.28,
    "multiple": 67.94
  },
  "FL": {
    "key": "FL",
    "basic": 52.02,
    "multiple": 63.68
  },
  "GA": {
    "key": "GA",
    "basic": 51.36,
    "multiple": 63.01
  },
  "IA": {
    "key": "IA",
    "multiple": 42.45,
    "basic": ""
  },
  "IL": {
    "key": "IL",
    "basic": 52.6,
    "multiple": 64.26
  },
  "IN": {
    "key": "IN",
    "basic": 52.13,
    "multiple": 63.79
  },
  "KY": {
    "key": "KY",
    "basic": 52.81,
    "multiple": 64.47
  },
  "LA": {
    "key": "LA",
    "basic": 50.05,
    "multiple": 61.71
  },
  "MA": {
    "key": "MA",
    "basic": 52.29,
    "multiple": 63.94
  },
  "MD": {
    "key": "MD",
    "basic": 52.33,
    "multiple": 63.99
  },
  "ME": {
    "key": "ME",
    "basic": 52.16,
    "multiple": 63.81
  },
  "MI": {
    "key": "MI",
    "basic": 52.63,
    "multiple": ""
  },
  "MN": {
    "key": "MN",
    "basic": 34.9,
    "multiple": 42.67
  },
  "MO": {
    "key": "MO",
    "basic": 52.97,
    "multiple": ""
  },
  "MS": {
    "key": "MS",
    "basic": 52.17,
    "multiple": 63.82
  },
  "NC": {
    "key": "NC",
    "basic": 52.43,
    "multiple": 64.09
  },
  "NH": {
    "key": "NH",
    "basic": 52.18,
    "multiple": 63.83
  },
  "NJ": {
    "key": "NJ",
    "basic": 51.94,
    "multiple": 63.59
  },
  "NY": {
    "key": "NY",
    "basic": 54.65,
    "multiple": 66.3
  },
  "OH": {
    "key": "OH",
    "basic": 51.05,
    "multiple": ""
  },
  "PA": {
    "key": "PA",
    "basic": 54.73,
    "multiple": 66.38
  },
  "RI": {
    "key": "RI",
    "basic": 52.64,
    "multiple": 64.29
  },
  "SC": {
    "key": "SC",
    "basic": 52.47,
    "multiple": 64.12
  },
  "TN": {
    "key": "TN",
    "basic": 52.14,
    "multiple": 63.79
  },
  "VA": {
    "key": "VA",
    "basic": 52.86,
    "multiple": 64.51
  },
  "VT": {
    "key": "VT",
    "basic": 52.18,
    "multiple": 63.84
  },
  "WI": {
    "key": "WI",
    "basic": 52.37,
    "multiple": 64.03
  },
  "WV": {
    "key": "WV",
    "basic": 52.55,
    "multiple": 64.2
  }
};

const ATerosionControl = {
  "Dozer": {
    "key": "Dozer",
    "cost": 145,
    "Notes": "average rate for under 150 hp bulldozer on 2022 MO Custom rates survey"
  },
  "Skid steer": {
    "key": "Skid steer",
    "cost": 100,
    "Notes": "median 2022 rate on MO Custom rate survey"
  },
  "Trackhoe": {
    "key": "Trackhoe",
    "cost": 115,
    "Notes": "median 2022 rate on MO Custom rate survey for 2-6 ton trackhoe"
  }
};

export const db = {
  coefficients: ATcoefficients,
  rates: ATrates,
  costDefaults: ATcostDefaults,
  herbicides: ATherbicides,
  implements: ATimplements,
  power: ATpower,
  seedList: ATseedList,
  stateRegions: ATstateRegions,
  commodities: ATcommodities,
  eqip: ATeqip,
  erosionControl: ATerosionControl,
};
