/* eslint-disable import/prefer-default-export */
/* eslint-disable max-len */
/* eslint-disable comma-dangle */
/* eslint-disable quote-props */
/* eslint-disable quotes */
const ATcoefficients = {
  "Air-carrier sprayer": {
    "key": "Air-carrier sprayer",
    "RF1": 0.2,
    "RF2": 1.6,
    "Life (hr)": 2000,
    "RV1": 0.8554,
    "RV2": 0.1177,
    "RV3": 0,
    "RV4": 0.0029,
    "RV5": 0.1274
  },
  "Bean puller-windrower": {
    "key": "Bean puller-windrower",
    "RF1": 0.2,
    "RF2": 1.6,
    "Life (hr)": 2000,
    "RV1": 0.7194,
    "RV2": 0.1102,
    "RV3": 0,
    "RV4": 0.003,
    "RV5": 0.1213
  },
  "Beet topper/stalk chopper": {
    "key": "Beet topper/stalk chopper",
    "RF1": 0.28,
    "RF2": 1.4,
    "Life (hr)": 1200,
    "RV1": 0.7194,
    "RV2": 0.1102,
    "RV3": 0,
    "RV4": 0.003,
    "RV5": 0.1213
  },
  "Boom type sprayer": {
    "key": "Boom type sprayer",
    "RF1": 0.41,
    "RF2": 1.3,
    "Life (hr)": 1500,
    "RV1": 0.8554,
    "RV2": 0.1177,
    "RV3": 0,
    "RV4": 0.0029,
    "RV5": 0.1274
  },
  "Chisel plow": {
    "key": "Chisel plow",
    "RF1": 0.28,
    "RF2": 1.4,
    "Life (hr)": 2000,
    "RV1": 0.6927,
    "RV2": 0.0703,
    "RV3": 0,
    "RV4": 0.0012,
    "RV5": 0.1223
  },
  "Combine (pulled)": {
    "key": "Combine (pulled)",
    "RF1": 0.12,
    "RF2": 2.3,
    "Life (hr)": 2000,
    "RV1": 1.054,
    "RV2": 0.1865,
    "RV3": 0.0068,
    "RV4": 0.0028,
    "RV5": 0.0847
  },
  "Combine (self propelled)": {
    "key": "Combine (self propelled)",
    "RF1": 0.04,
    "RF2": 2.1,
    "Life (hr)": 3000,
    "RV1": 1.01361018,
    "RV2": 0.174199608,
    "RV3": 0.007696442,
    "RV4": 0.000749051,
    "RV5": 0
  },
  "Combine (self propelled*)": {
    "key": "Combine (self propelled*)",
    "RF1": 0.04,
    "RF2": 2.1,
    "Life (hr)": 3000,
    "RV1": 1.054,
    "RV2": 0.1865,
    "RV3": 0.0068,
    "RV4": 0.0028,
    "RV5": 0.0847
  },
  "Combine (self propelled**)": {
    "key": "Combine (self propelled**)",
    "RF1": 0.04,
    "RF2": 2.1,
    "Life (hr)": 3000,
    "RV1": 1.054,
    "RV2": 0.1865,
    "RV3": 0.0068,
    "RV4": 0.0028,
    "RV5": 0.0847
  },
  "Combine (self propelled***)": {
    "key": "Combine (self propelled***)",
    "RF1": 0.04,
    "RF2": 2.1,
    "Life (hr)": 3000,
    "RV1": 1.01905018,
    "RV2": 0.174199608,
    "RV3": 0.007696442,
    "RV4": 0.000749051,
    "RV5": 0
  },
  "Corn picker sheller": {
    "key": "Corn picker sheller",
    "RF1": 0.14,
    "RF2": 2.3,
    "Life (hr)": 2000,
    "RV1": 1.054,
    "RV2": 0.1865,
    "RV3": 0.0068,
    "RV4": 0.0028,
    "RV5": 0.0847
  },
  "Cotton picker": {
    "key": "Cotton picker",
    "RF1": 0.11,
    "RF2": 1.8,
    "Life (hr)": 3000,
    "RV1": 1.054,
    "RV2": 0.1865,
    "RV3": 0.0068,
    "RV4": 0.0028,
    "RV5": 0.0847
  },
  "Fertilizer spreader": {
    "key": "Fertilizer spreader",
    "RF1": 0.63,
    "RF2": 1.3,
    "Life (hr)": 1200,
    "RV1": 0.8635,
    "RV2": 0.1288,
    "RV3": 0,
    "RV4": 0.0017,
    "RV5": 0.1569
  },
  "Field cultivators": {
    "key": "Field cultivators",
    "RF1": 0.27,
    "RF2": 1.4,
    "Life (hr)": 2000,
    "RV1": 0.6927,
    "RV2": 0.0703,
    "RV3": 0,
    "RV4": 0.0012,
    "RV5": 0.1223
  },
  "Forage blower": {
    "key": "Forage blower",
    "RF1": 0.22,
    "RF2": 1.8,
    "Life (hr)": 1500,
    "RV1": 0.6529,
    "RV2": 0.1511,
    "RV3": 0,
    "RV4": 0.0078,
    "RV5": 0.1235
  },
  "Forage harvester": {
    "key": "Forage harvester",
    "RF1": 0.15,
    "RF2": 1.6,
    "Life (hr)": 2500,
    "RV1": 0.6529,
    "RV2": 0.1511,
    "RV3": 0,
    "RV4": 0.0078,
    "RV5": 0.1235
  },
  "Forage harvester (SP)": {
    "key": "Forage harvester (SP)",
    "RF1": 0.03,
    "RF2": 2,
    "Life (hr)": 4000,
    "RV1": 0.6529,
    "RV2": 0.1511,
    "RV3": 0,
    "RV4": 0.0078,
    "RV5": 0.1235
  },
  "Forage wagons": {
    "key": "Forage wagons",
    "RF1": 0.16,
    "RF2": 1.6,
    "Life (hr)": 2000,
    "RV1": 0.8091,
    "RV2": 0.1109,
    "RV3": 0,
    "RV4": 0.0014,
    "RV5": 0.1267
  },
  "Four wheel drive tractors & crawlers": {
    "key": "Four wheel drive tractors & crawlers",
    "RF1": 0.003,
    "RF2": 2,
    "Life (hr)": 16000,
    "RV1": 0.8641,
    "RV2": 0.1564,
    "RV3": 0.0034,
    "RV4": 0.0046,
    "RV5": 0.086
  },
  "Grain drill": {
    "key": "Grain drill",
    "RF1": 0.32,
    "RF2": 2.1,
    "Life (hr)": 1500,
    "RV1": 1.2211,
    "RV2": 0.1737,
    "RV3": 0,
    "RV4": -0.0017,
    "RV5": 0.1264
  },
  "Heavy Duty disk harrow": {
    "key": "Heavy Duty disk harrow",
    "RF1": 0.18,
    "RF2": 1.7,
    "Life (hr)": 2000,
    "RV1": 0.7194,
    "RV2": 0.1102,
    "RV3": 0,
    "RV4": 0.003,
    "RV5": 0.1213
  },
  "Large rectangular baler": {
    "key": "Large rectangular baler",
    "RF1": 0.1,
    "RF2": 1.8,
    "Life (hr)": 3000,
    "RV1": 0.8091,
    "RV2": 0.1109,
    "RV3": 0,
    "RV4": 0.0014,
    "RV5": 0.1267
  },
  "Large round baler": {
    "key": "Large round baler",
    "RF1": 0.43,
    "RF2": 1.8,
    "Life (hr)": 1500,
    "RV1": 0.8091,
    "RV2": 0.1109,
    "RV3": 0,
    "RV4": 0.0014,
    "RV5": 0.1267
  },
  "Manure handling equipment": {
    "key": "Manure handling equipment",
    "RF1": 0.16,
    "RF2": 1.6,
    "Life (hr)": 2000,
    "RV1": 0.8635,
    "RV2": 0.1288,
    "RV3": 0,
    "RV4": 0.0017,
    "RV5": 0.1569
  },
  "Mech. front wheel drive tractors": {
    "key": "Mech. front wheel drive tractors",
    "RF1": 0.005,
    "RF2": 2,
    "Life (hr)": 16000,
    "RV1": 0.8641,
    "RV2": 0.1564,
    "RV3": 0.0034,
    "RV4": 0.0046,
    "RV5": 0.086
  },
  "Moldboard plows": {
    "key": "Moldboard plows",
    "RF1": 0.29,
    "RF2": 1.8,
    "Life (hr)": 2000,
    "RV1": 0.6927,
    "RV2": 0.0703,
    "RV3": 0,
    "RV4": 0.0012,
    "RV5": 0.1223
  },
  "Mower": {
    "key": "Mower",
    "RF1": 0.46,
    "RF2": 1.7,
    "Life (hr)": 2000,
    "RV1": 0.9023,
    "RV2": 0.0943,
    "RV3": 0,
    "RV4": -0.0004,
    "RV5": 0.1073
  },
  "Mower (rotary)": {
    "key": "Mower (rotary)",
    "RF1": 0.44,
    "RF2": 2,
    "Life (hr)": 2000,
    "RV1": 0.9023,
    "RV2": 0.0943,
    "RV3": 0,
    "RV4": -0.0004,
    "RV5": 0.1073
  },
  "Mower-conditioner": {
    "key": "Mower-conditioner",
    "RF1": 0.18,
    "RF2": 1.6,
    "Life (hr)": 2500,
    "RV1": 0.7243,
    "RV2": 0.1127,
    "RV3": 0,
    "RV4": 0.0034,
    "RV5": 0.1188
  },
  "Mower-conditioner (rotary)": {
    "key": "Mower-conditioner (rotary)",
    "RF1": 0.16,
    "RF2": 2,
    "Life (hr)": 2500,
    "RV1": 0.7243,
    "RV2": 0.1127,
    "RV3": 0,
    "RV4": 0.0034,
    "RV5": 0.1188
  },
  "Mulcher-packer": {
    "key": "Mulcher-packer",
    "RF1": 0.16,
    "RF2": 1.3,
    "Life (hr)": 2000,
    "RV1": 0.7194,
    "RV2": 0.1102,
    "RV3": 0,
    "RV4": 0.003,
    "RV5": 0.1213
  },
  "None": {
    "key": "None",
    "RF1": "",
    "RF2": "",
    "Life (hr)": "",
    "RV1": "",
    "RV2": "",
    "RV3": "",
    "RV4": "",
    "RV5": ""
  },
  "Potato harvester": {
    "key": "Potato harvester",
    "RF1": 0.19,
    "RF2": 1.4,
    "Life (hr)": 2500,
    "RV1": 0.8091,
    "RV2": 0.1109,
    "RV3": 0,
    "RV4": 0.0014,
    "RV5": 0.1267
  },
  "Rectangular baler": {
    "key": "Rectangular baler",
    "RF1": 0.23,
    "RF2": 1.8,
    "Life (hr)": 2000,
    "RV1": 0.8091,
    "RV2": 0.1109,
    "RV3": 0,
    "RV4": 0.0014,
    "RV5": 0.1267
  },
  "Roller packer": {
    "key": "Roller packer",
    "RF1": 0.16,
    "RF2": 1.3,
    "Life (hr)": 2000,
    "RV1": 0.7194,
    "RV2": 0.1102,
    "RV3": 0,
    "RV4": 0.003,
    "RV5": 0.1213
  },
  "Rotary hoe": {
    "key": "Rotary hoe",
    "RF1": 0.23,
    "RF2": 1.4,
    "Life (hr)": 2000,
    "RV1": 0.6927,
    "RV2": 0.0703,
    "RV3": 0,
    "RV4": 0.0012,
    "RV5": 0.1223
  },
  "Rotary tiller": {
    "key": "Rotary tiller",
    "RF1": 0.36,
    "RF2": 2,
    "Life (hr)": 1500,
    "RV1": 0.7194,
    "RV2": 0.1102,
    "RV3": 0,
    "RV4": 0.003,
    "RV5": 0.1213
  },
  "Row crop cultivator": {
    "key": "Row crop cultivator",
    "RF1": 0.17,
    "RF2": 2.2,
    "Life (hr)": 2000,
    "RV1": 0.6927,
    "RV2": 0.0703,
    "RV3": 0,
    "RV4": 0.0012,
    "RV5": 0.1223
  },
  "Row crop planter": {
    "key": "Row crop planter",
    "RF1": 0.32,
    "RF2": 2.1,
    "Life (hr)": 1500,
    "RV1": 0.8554,
    "RV2": 0.1177,
    "RV3": 0,
    "RV4": 0.0029,
    "RV5": 0.1274
  },
  "Side delivery rake": {
    "key": "Side delivery rake",
    "RF1": 0.17,
    "RF2": 1.4,
    "Life (hr)": 2500,
    "RV1": 0.8091,
    "RV2": 0.1109,
    "RV3": 0,
    "RV4": 0.0014,
    "RV5": 0.1267
  },
  "Skid-steer loader": {
    "key": "Skid-steer loader",
    "RF1": 0.007,
    "RF2": 2,
    "Life (hr)": 3000,
    "RV1": 0.7275,
    "RV2": 0.0806,
    "RV3": 0.0025,
    "RV4": 0.004,
    "RV5": 0.0812
  },
  "Spring tooth harrow": {
    "key": "Spring tooth harrow",
    "RF1": 0.27,
    "RF2": 1.4,
    "Life (hr)": 2000,
    "RV1": 0.6927,
    "RV2": 0.0703,
    "RV3": 0,
    "RV4": 0.0012,
    "RV5": 0.1223
  },
  "Sugar beet harvester": {
    "key": "Sugar beet harvester",
    "RF1": 0.59,
    "RF2": 1.3,
    "Life (hr)": 1500,
    "RV1": 0.7194,
    "RV2": 0.1102,
    "RV3": 0,
    "RV4": 0.003,
    "RV5": 0.1213
  },
  "Tandem disk harrow": {
    "key": "Tandem disk harrow",
    "RF1": 0.18,
    "RF2": 1.7,
    "Life (hr)": 2000,
    "RV1": 0.7194,
    "RV2": 0.1102,
    "RV3": 0,
    "RV4": 0.003,
    "RV5": 0.1213
  },
  "Total mixed ration mixer wagons": {
    "key": "Total mixed ration mixer wagons",
    "RF1": 0.015,
    "RF2": 1.6,
    "Life (hr)": 5000,
    "RV1": 0.8091,
    "RV2": 0.1109,
    "RV3": 0,
    "RV4": 0.0014,
    "RV5": 0.1267
  },
  "Two wheel drive tractors": {
    "key": "Two wheel drive tractors",
    "RF1": 0.1,
    "RF2": 1.3,
    "Life (hr)": 1500,
    "RV1": 0.8554,
    "RV2": 0.1177,
    "RV3": 0,
    "RV4": 0.0029,
    "RV5": 0.1274
  },
  "Two wheel drive tractors, 81-120 HP": {
    "key": "Two wheel drive tractors, 81-120 HP",
    "RF1": 0.007,
    "RF2": 2,
    "Life (hr)": 12000,
    "RV1": 0.8469,
    "RV2": 0.1103,
    "RV3": 0.0036,
    "RV4": 0.0042,
    "RV5": 0.1099
  },
  "Two wheel drive tractors, 121-145 HP": {
    "key": "Two wheel drive tractors, 121-145 HP",
    "RF1": 0.007,
    "RF2": 2,
    "Life (hr)": 12000,
    "RV1": 0.8304,
    "RV2": 0.1207,
    "RV3": 0.0021,
    "RV4": 0.0048,
    "RV5": 0.1074
  },
  "Two wheel drive tractors, 146+ HP TWD": {
    "key": "Two wheel drive tractors, 146+ HP TWD",
    "RF1": 0.007,
    "RF2": 2,
    "Life (hr)": 12000,
    "RV1": 0.8664,
    "RV2": 0.1502,
    "RV3": 0.0033,
    "RV4": 0.0055,
    "RV5": 0.1098
  },
  "Two wheel drive tractors, under 80 HP": {
    "key": "Two wheel drive tractors, under 80 HP",
    "RF1": 0.007,
    "RF2": 2,
    "Life (hr)": 12000,
    "RV1": 0.8493,
    "RV2": 0.0966,
    "RV3": 0.0059,
    "RV4": 0.0038,
    "RV5": 0.1062
  },
  "Wagon": {
    "key": "Wagon",
    "RF1": 0.19,
    "RF2": 1.3,
    "Life (hr)": 3000,
    "RV1": 0.8091,
    "RV2": 0.1109,
    "RV3": 0,
    "RV4": 0.0014,
    "RV5": 0.1267
  },
  "Windrower (SP)": {
    "key": "Windrower (SP)",
    "RF1": 0.06,
    "RF2": 2,
    "Life (hr)": 3000,
    "RV1": 0.7243,
    "RV2": 0.1127,
    "RV3": 0,
    "RV4": 0.0034,
    "RV5": 0.1188
  }
};

const ATrates = {
  "conversion": {
    "key": "conversion",
    "description": "Acres Conversion factor (=43560 ft2/ac * mi/5280ft)",
    "value": 8.25,
    "Notes": ""
  },
  "deflator": {
    "key": "deflator",
    "description": "GDP implicit price deflator, 2020 4th quarter",
    "value": 122.27,
    "Notes": "Source: MachData2024 from Lazarus"
  },
  "deflator1996": {
    "key": "deflator1996",
    "description": "GDP implicit price deflator, 1996",
    "value": 68.16,
    "Notes": "Source: MachData2024 from Lazarus"
  },
  "forecast": {
    "key": "forecast",
    "description": "2020 U.S. net farm income forecast ($ billions)",
    "value": 116.1,
    "Notes": "Source: MachData2024 from Lazarus"
  },
  "fuel": {
    "key": "fuel",
    "description": "Fuel price, $/gallon",
    "value": 2.98,
    "Notes": "Farm diesel price from MachData 2024"
  },
  "horsepower": {
    "key": "horsepower",
    "description": "Self propelled assumed horsepower (for fuel calcs)",
    "value": 80,
    "Notes": "Source: MachData2024 from Lazarus"
  },
  "inflation": {
    "key": "inflation",
    "description": "Inflation Rate, % per year",
    "value": 0,
    "Notes": "Source: MachData2024  from Lazarus"
  },
  "insurance": {
    "key": "insurance",
    "description": "Insurance Rate",
    "value": 0.0085,
    "Notes": "Source: MachData2024  from Lazarus"
  },
  "interest": {
    "key": "interest",
    "description": "Interest Rate, % of average investment",
    "value": 0.08,
    "Notes": "Aug 2024 Operating loan rate from KC Fed Reserve"
  },
  "K2O": {
    "key": "K2O",
    "description": "$ per pound of K2O",
    "value": 0.39,
    "Notes": "Average Illinois Production Cost Report on 8/23/24"
  },
  "lubrication": {
    "key": "lubrication",
    "description": "Lubrication cost, % of fuel",
    "value": 0.1,
    "Notes": "Source: MachData2024  from Lazarus"
  },
  "Nitrogen": {
    "key": "Nitrogen",
    "description": "$ per pound of N",
    "value": 0.54,
    "Notes": "Average Illinois Production Cost Report on 8/23/24"
  },
  "P2O5": {
    "key": "P2O5",
    "description": "$ per pound of P2O5",
    "value": 0.58,
    "Notes": "Average Illinois Production Cost Report on 8/23/24"
  },
  "projected": {
    "key": "projected",
    "description": "Real Net Farm Income projected at trade-in, in $ billion 1996 dollars",
    "value": 65,
    "Notes": "Source: MachData2024 from Lazarus"
  },
  "property": {
    "key": "property",
    "description": "Property taxes",
    "value": 0.0025,
    "Notes": "Note: this varies by state."
  },
  "skilled": {
    "key": "skilled",
    "description": "Skilled Labor Rate $/hr.",
    "value": 18.25,
    "Notes": "May 2024 USDA Farm Labor wage for field workers"
  },
  "storage": {
    "key": "storage",
    "description": "Storage Cost/Sq. Foot of Space",
    "value": 0.97,
    "Notes": "Source: MachData2024  from Lazarus"
  }
};

const ATcostDefaults = {
  "Hire custom operator|termination.chemical": {
    "key": "Hire custom operator",
    "cost": 8,
    "Notes": "Median broadcast, self propelled custom charge in 2024 ISU Custom Rates",
    "screen": "termination.chemical",
    "order": ""
  },
  "Anhydrous ammonia injection": {
    "key": "Anhydrous ammonia injection",
    "cost": 15,
    "Notes": "Median anhydrous injection custom charge in 2024 ISU Custom Rates",
    "screen": "",
    "order": ""
  },
  "Hire custom operator|seedbed": {
    "key": "Hire custom operator",
    "cost": 18,
    "Notes": "Median tandem disk custom charge in 2024 ISU Custom Rates",
    "screen": "seedbed",
    "order": ""
  },
  "Hire custom operator|termination.roller": {
    "key": "Hire custom operator",
    "cost": 15,
    "Notes": "Calculated full cost of 6 row CC roller in CC DST mockup 7-20-22",
    "screen": "termination.roller",
    "order": ""
  },
  "Dry Fertilizer application": {
    "key": "Dry Fertilizer application",
    "cost": 7,
    "Notes": "Median dry bulk fertilizer custom charge in 2024 ISU Custom Rates",
    "screen": "",
    "order": ""
  },
  "Liquid fertilizer application": {
    "key": "Liquid fertilizer application",
    "cost": 7.5,
    "Notes": "Median liquid fert spraying custom charge in 2024 ISU Custom Rates",
    "screen": "",
    "order": ""
  },
  "Aerial spraying": {
    "key": "Aerial spraying",
    "cost": 10.25,
    "Notes": "Median aerial spraying custom charge in 2024 ISU Custom Rates",
    "screen": "",
    "order": ""
  },
  "Drone spraying": {
    "key": "Drone spraying",
    "cost": 15,
    "Notes": "Average drone seeding custom charge in 2024 UNL Custom Rates",
    "screen": "",
    "order": ""
  },
  "Drill or planter|planting": {
    "key": "Drill or planter",
    "cost": 19,
    "Notes": "Median drilling cover crop seed custom charge in 2024 ISU Custom Rates",
    "screen": "planting",
    "order": ""
  },
  "Hire custom operator|termination.tillage": {
    "key": "Hire custom operator",
    "cost": 23,
    "Notes": "Median disk/chisel plow custom charge in 2024 ISU Custom Rates",
    "screen": "termination.tillage",
    "order": ""
  },
  "Hire custom operator|tillage": {
    "key": "Hire custom operator",
    "cost": 23,
    "Notes": "Median disk/chisel plow custom charge in 2024 ISU Custom Rates",
    "screen": "tillage",
    "order": ""
  },
  "Hire custom operator|herbicide": {
    "key": "Hire custom operator",
    "cost": 8,
    "Notes": "Median broadcast, self propelled custom charge in 2024 ISU Custom Rates",
    "screen": "herbicide",
    "order": ""
  },
  "Broadcast seeding|planting": {
    "key": "Broadcast seeding",
    "cost": 13,
    "Notes": "Median seeding grass/broadcast custom charge in 2024 ISU Custom Rates",
    "screen": "planting",
    "order": 1
  },
  "Aerial seeding|planting": {
    "key": "Aerial seeding",
    "cost": 14,
    "Notes": "Median aerial seeding custom charge in 2024 ISU Custom Rates",
    "screen": "planting",
    "order": 2
  },
  "Drone seeding|planting": {
    "key": "Drone seeding",
    "cost": 19,
    "Notes": "Median drilling cover crop seed custom charge in 2024 ISU Custom Rates",
    "screen": "planting",
    "order": 3
  }
};

const ATherbicides = {
  "2,4-D": {
    "key": "2,4-D",
    "Rate": 1,
    "Unit (rate)": "lb/acre",
    "Cost ($)": "5",
    "Unit (cost)": "lb"
  },
  "atrazine": {
    "key": "atrazine",
    "Rate": 2,
    "Unit (rate)": "lb/acre",
    "Cost ($)": "4",
    "Unit (cost)": "lb"
  },
  "dicamba": {
    "key": "dicamba",
    "Rate": 3,
    "Unit (rate)": "lb/acre",
    "Cost ($)": "3",
    "Unit (cost)": "lb"
  },
  "glyphosate": {
    "key": "glyphosate",
    "Rate": 4,
    "Unit (rate)": "lb/acre",
    "Cost ($)": "2",
    "Unit (cost)": "lb"
  },
  "liberty": {
    "key": "liberty",
    "Rate": 5,
    "Unit (rate)": "lb/acre",
    "Cost ($)": "1",
    "Unit (cost)": "lb"
  }
};

const ATimplements = {
  "Air Seeder Drill w/Cart; 52 Ft": {
    "key": "Air Seeder Drill w/Cart; 52 Ft",
    "type": "Planting",
    "name": "Air Seeder Drill w/Cart",
    "size1": 52,
    "unit1": "Ft",
    "default power unit": "260 HP MFWD Tractor",
    "purchase price": 342000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 80,
    "default ASABE category": "Grain drill",
    "field speed (m/h)": 5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 270,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Boom Sprayer, Pull-Type; 90 Ft": {
    "key": "Boom Sprayer, Pull-Type; 90 Ft",
    "type": "Chemical",
    "name": "Boom Sprayer, Pull-Type",
    "size1": 90,
    "unit1": "Ft",
    "default power unit": "130 HP MFWD Tractor",
    "purchase price": 54500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 25,
    "default ASABE category": "Boom type sprayer",
    "field speed (m/h)": 6.5,
    "field efficiency": 0.65,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.25,
    "labortype": "Skilled",
    "shed (ft^2)": 400,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Boom Sprayer, Self-Propelled; 90 Ft": {
    "key": "Boom Sprayer, Self-Propelled; 90 Ft",
    "type": "Chemical",
    "name": "Boom Sprayer, Self-Propelled",
    "size1": 90,
    "unit1": "Ft",
    "default power unit": "130 HP Self Propelled",
    "purchase price": 673000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Two wheel drive tractors",
    "field speed (m/h)": 7,
    "field efficiency": 0.65,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.25,
    "labortype": "Skilled",
    "shed (ft^2)": 200,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Chisel Plow, Front Dsk; 16.3 Ft": {
    "key": "Chisel Plow, Front Dsk; 16.3 Ft",
    "type": "Tillage",
    "name": "Chisel Plow, Front Dsk",
    "size1": 16.25,
    "unit1": "Ft",
    "default power unit": "200 HP MFWD Tractor",
    "purchase price": 38000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 80,
    "default ASABE category": "Tandem disk harrow",
    "field speed (m/h)": 5,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 225,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Chisel Plow, Front Dsk; 21.3 Ft Fold": {
    "key": "Chisel Plow, Front Dsk; 21.3 Ft Fold",
    "type": "Tillage",
    "name": "Chisel Plow, Front Dsk",
    "size1": 21.25,
    "unit1": "Ft Fold",
    "default power unit": "310 HP 4WD Tractor",
    "purchase price": 59500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 80,
    "default ASABE category": "Tandem disk harrow",
    "field speed (m/h)": 5,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 225,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Chisel Plow; 15 Ft": {
    "key": "Chisel Plow; 15 Ft",
    "type": "Tillage",
    "name": "Chisel Plow",
    "size1": 15,
    "unit1": "Ft",
    "default power unit": "130 HP MFWD Tractor",
    "purchase price": 40000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 60,
    "default ASABE category": "Chisel plow",
    "field speed (m/h)": 5,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 225,
    "Notes": "No longer reported by Lazarus. Price increased proportionately.",
    "size2": "",
    "unit2": ""
  },
  "Chisel Plow; 23 Ft": {
    "key": "Chisel Plow; 23 Ft",
    "type": "Tillage",
    "name": "Chisel Plow",
    "size1": 23,
    "unit1": "Ft",
    "default power unit": "200 HP MFWD Tractor",
    "purchase price": 59500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 60,
    "default ASABE category": "Chisel plow",
    "field speed (m/h)": 5,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 250,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Chisel Plow; 37 Ft": {
    "key": "Chisel Plow; 37 Ft",
    "type": "Tillage",
    "name": "Chisel Plow",
    "size1": 37,
    "unit1": "Ft",
    "default power unit": "310 HP 4WD Tractor",
    "purchase price": 87000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 60,
    "default ASABE category": "Chisel plow",
    "field speed (m/h)": 5,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 370,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Chisel Plow; 57 Ft": {
    "key": "Chisel Plow; 57 Ft",
    "type": "Tillage",
    "name": "Chisel Plow",
    "size1": 57,
    "unit1": "Ft",
    "default power unit": "425 HP 4WD Tractor",
    "purchase price": 146000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 60,
    "default ASABE category": "Chisel plow",
    "field speed (m/h)": 5,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 370,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Combine Belt Pickup Hd; 23 Ft": {
    "key": "Combine Belt Pickup Hd; 23 Ft",
    "type": "Harvest",
    "name": "Combine Belt Pickup Hd",
    "size1": 23,
    "unit1": "Ft",
    "default power unit": "275 HP Combine",
    "purchase price": 44000,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 106.52173913043478,
    "default ASABE category": "Combine (self propelled)",
    "field speed (m/h)": 4,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 75,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Combine Chopping Corn Hd; 8 Row; 20 Ft": {
    "key": "Combine Chopping Corn Hd; 8 Row; 20 Ft",
    "type": "Harvest",
    "name": "Combine Chopping Corn Hd",
    "size1": 20,
    "unit1": "Ft",
    "size2": "8",
    "unit2": "Row",
    "default power unit": "275 HP Combine",
    "purchase price": 115000,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Beet topper/stalk chopper",
    "field speed (m/h)": 4,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 160,
    "Notes": "Source: MachData2024  from Lazarus"
  },
  "Combine Chopping Corn Hd; 12 Row; 22 Ft": {
    "key": "Combine Chopping Corn Hd; 12 Row; 22 Ft",
    "type": "Harvest",
    "name": "Combine Chopping Corn Hd",
    "size1": 22,
    "unit1": "Ft",
    "size2": "12",
    "unit2": "Row",
    "default power unit": "440 HP Combine",
    "purchase price": 170000,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Beet topper/stalk chopper",
    "field speed (m/h)": 4,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 160,
    "Notes": "Source: MachData2024  from Lazarus"
  },
  "Combine Chopping Corn Hd; 12 Row; 30 Ft": {
    "key": "Combine Chopping Corn Hd; 12 Row; 30 Ft",
    "type": "Harvest",
    "name": "Combine Chopping Corn Hd",
    "size1": 30,
    "unit1": "Ft",
    "size2": "12",
    "unit2": "Row",
    "default power unit": "440 HP Combine",
    "purchase price": 174000,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Beet topper/stalk chopper",
    "field speed (m/h)": 4,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 160,
    "Notes": "Source: MachData2024  from Lazarus"
  },
  "Combine Corn Hd; 6 Row; 15 Ft": {
    "key": "Combine Corn Hd; 6 Row; 15 Ft",
    "type": "Harvest",
    "name": "Combine Corn Hd",
    "size1": 15,
    "unit1": "Ft",
    "size2": "6",
    "unit2": "Row",
    "default power unit": "275 HP Combine",
    "purchase price": 66000,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Combine (self propelled)",
    "field speed (m/h)": 4,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 120,
    "Notes": "Source: MachData2024  from Lazarus"
  },
  "Combine Corn Hd; 8 Row; 20 Ft": {
    "key": "Combine Corn Hd; 8 Row; 20 Ft",
    "type": "Harvest",
    "name": "Combine Corn Hd",
    "size1": 20,
    "unit1": "Ft",
    "size2": "8",
    "unit2": "Row",
    "default power unit": "275 HP Combine",
    "purchase price": 85500,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Combine (self propelled)",
    "field speed (m/h)": 4,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 160,
    "Notes": "Source: MachData2024  from Lazarus"
  },
  "Combine Corn Hd; 12 Row; 22 Ft": {
    "key": "Combine Corn Hd; 12 Row; 22 Ft",
    "type": "Harvest",
    "name": "Combine Corn Hd",
    "size1": 22,
    "unit1": "Ft",
    "size2": "12",
    "unit2": "Row",
    "default power unit": "375 HP Combine",
    "purchase price": 129000,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Combine (self propelled)",
    "field speed (m/h)": 4,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 160,
    "Notes": "Source: MachData2024  from Lazarus"
  },
  "Combine Corn Hd; 12 Row; 30 Ft": {
    "key": "Combine Corn Hd; 12 Row; 30 Ft",
    "type": "Harvest",
    "name": "Combine Corn Hd",
    "size1": 30,
    "unit1": "Ft",
    "size2": "12",
    "unit2": "Row",
    "default power unit": "375 HP Combine",
    "purchase price": 131000,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Combine (self propelled)",
    "field speed (m/h)": 4,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 160,
    "Notes": "Source: MachData2024  from Lazarus"
  },
  "Combine Flex Platform; 20 Ft": {
    "key": "Combine Flex Platform; 20 Ft",
    "type": "Harvest",
    "name": "Combine Flex Platform",
    "size1": 20,
    "unit1": "Ft",
    "default power unit": "275 HP Combine",
    "purchase price": 36000,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 199.99999999999997,
    "default ASABE category": "Combine (self propelled)",
    "field speed (m/h)": 3.5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 108,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Combine Flex Platform; 25 Ft": {
    "key": "Combine Flex Platform; 25 Ft",
    "type": "Harvest",
    "name": "Combine Flex Platform",
    "size1": 25,
    "unit1": "Ft",
    "default power unit": "375 HP Combine",
    "purchase price": 43500,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Combine (self propelled)",
    "field speed (m/h)": 3.5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 108,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Combine Flex Platform; 30 Ft": {
    "key": "Combine Flex Platform; 30 Ft",
    "type": "Harvest",
    "name": "Combine Flex Platform",
    "size1": 30,
    "unit1": "Ft",
    "default power unit": "375 HP Combine",
    "purchase price": 51000,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Combine (self propelled)",
    "field speed (m/h)": 3.5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 108,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Cover Crop Roller; 8 Ft": {
    "key": "Cover Crop Roller; 8 Ft",
    "type": "Termination",
    "name": "Cover Crop Roller",
    "size1": 8,
    "unit1": "Ft",
    "default power unit": "60 HP Tractor",
    "purchase price": 6000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Field cultivators",
    "field speed (m/h)": 6,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 130,
    "Notes": "Drew Kientzy 2023 price; assumed ASAE coefficients",
    "size2": "",
    "unit2": ""
  },
  "Cover Crop Roller; 10.5 Ft": {
    "key": "Cover Crop Roller; 10.5 Ft",
    "type": "Termination",
    "name": "Cover Crop Roller",
    "size1": 10.5,
    "unit1": "Ft",
    "default power unit": "75 HP Tractor",
    "purchase price": 6900,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Field cultivators",
    "field speed (m/h)": 6,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 150,
    "Notes": "Drew Kientzy 2023 price; assumed ASAE coefficients",
    "size2": "",
    "unit2": ""
  },
  "Cover Crop Roller; 15.5 Ft": {
    "key": "Cover Crop Roller; 15.5 Ft",
    "type": "Termination",
    "name": "Cover Crop Roller",
    "size1": 15.5,
    "unit1": "Ft",
    "default power unit": "105 HP MFWD Tractor",
    "purchase price": 9900,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Field cultivators",
    "field speed (m/h)": 6,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 200,
    "Notes": "Drew Kientzy 2023 price; assumed ASAE coefficients",
    "size2": "",
    "unit2": ""
  },
  "Cover Crop Roller; 30 Ft Fold": {
    "key": "Cover Crop Roller; 30 Ft Fold",
    "type": "Termination",
    "name": "Cover Crop Roller",
    "size1": 30,
    "unit1": "Ft Fold",
    "default power unit": "160 HP MFWD Tractor",
    "purchase price": 34800,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Field cultivators",
    "field speed (m/h)": 6,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 300,
    "Notes": "Drew Kientzy 2023 price; assumed ASAE coefficients",
    "size2": "",
    "unit2": ""
  },
  "Field Cultivator; 23 Ft": {
    "key": "Field Cultivator; 23 Ft",
    "type": "Tillage",
    "name": "Field Cultivator",
    "size1": 23,
    "unit1": "Ft",
    "default power unit": "160 HP MFWD Tractor",
    "purchase price": 54000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Field cultivators",
    "field speed (m/h)": 7,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 200,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Field Cultivator; 47 Ft": {
    "key": "Field Cultivator; 47 Ft",
    "type": "Tillage",
    "name": "Field Cultivator",
    "size1": 47,
    "unit1": "Ft",
    "default power unit": "310 HP 4WD Tractor",
    "purchase price": 111000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Field cultivators",
    "field speed (m/h)": 7,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 400,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Field Cultivator; 60 Ft": {
    "key": "Field Cultivator; 60 Ft",
    "type": "Tillage",
    "name": "Field Cultivator",
    "size1": 60,
    "unit1": "Ft",
    "default power unit": "425 HP 4WD Tractor",
    "purchase price": 139000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Field cultivators",
    "field speed (m/h)": 7,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 400,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Forage Harvester, Pull-Type w/Corn Head; 3 Row; 7.5 Ft": {
    "key": "Forage Harvester, Pull-Type w/Corn Head; 3 Row; 7.5 Ft",
    "type": "Harvest",
    "name": "Forage Harvester, Pull-Type w/Corn Head",
    "size1": 7.5,
    "unit1": "Ft",
    "size2": "3",
    "unit2": "Row",
    "default power unit": "160 HP MFWD Tractor",
    "purchase price": 96500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Forage harvester",
    "field speed (m/h)": 3.5,
    "field efficiency": 0.65,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 140,
    "Notes": "Source: MachData2024  from Lazarus"
  },
  "Forage Harvester, Pull-Type w/Pickup Head; 12 Ft": {
    "key": "Forage Harvester, Pull-Type w/Pickup Head; 12 Ft",
    "type": "Harvest",
    "name": "Forage Harvester, Pull-Type w/Pickup Head",
    "size1": 12,
    "unit1": "Ft",
    "default power unit": "105 HP MFWD Tractor",
    "purchase price": 84500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Forage harvester",
    "field speed (m/h)": 3.5,
    "field efficiency": 0.65,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 140,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Forage Harvester, Self-Prop Corn Head; 6 Row; 15 Ft": {
    "key": "Forage Harvester, Self-Prop Corn Head; 6 Row; 15 Ft",
    "type": "Harvest",
    "name": "Forage Harvester, Self-Prop Corn Head",
    "size1": 15,
    "unit1": "Ft",
    "size2": "6",
    "unit2": "Row",
    "default power unit": "625 HP SP Forage Harvester Base Unit",
    "purchase price": 107000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Forage harvester (SP)",
    "field speed (m/h)": 4,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 300,
    "Notes": "Source: MachData2024  from Lazarus"
  },
  "Forage Harvester, Self-Prop Corn Head; 8 Row; 20 Ft": {
    "key": "Forage Harvester, Self-Prop Corn Head; 8 Row; 20 Ft",
    "type": "Harvest",
    "name": "Forage Harvester, Self-Prop Corn Head",
    "size1": 20,
    "unit1": "Ft",
    "size2": "8",
    "unit2": "Row",
    "default power unit": "625 HP SP Forage Harvester Base Unit",
    "purchase price": 141000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Forage harvester (SP)",
    "field speed (m/h)": 4,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 300,
    "Notes": "Source: MachData2024  from Lazarus"
  },
  "Forage Harvester, Self-Prop Pickup Head (2X windrows); 24 Ft": {
    "key": "Forage Harvester, Self-Prop Pickup Head (2X windrows); 24 Ft",
    "type": "Harvest",
    "name": "Forage Harvester, Self-Prop Pickup Head (2X windrows)",
    "size1": 24,
    "unit1": "Ft",
    "default power unit": "625 HP SP Forage Harvester Base Unit",
    "purchase price": 35000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Forage harvester (SP)",
    "field speed (m/h)": 4,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 300,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Forage Harvester, Self-Prop Pickup Head; 12 Ft": {
    "key": "Forage Harvester, Self-Prop Pickup Head; 12 Ft",
    "type": "Harvest",
    "name": "Forage Harvester, Self-Prop Pickup Head",
    "size1": 12,
    "unit1": "Ft",
    "default power unit": "400 HP SP Forage Harvester Base Unit",
    "purchase price": 35000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Forage harvester (SP)",
    "field speed (m/h)": 4,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 300,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Grain Cart; 30 Ft": {
    "key": "Grain Cart; 30 Ft",
    "type": "Harvest",
    "name": "Grain Cart",
    "size1": 30,
    "unit1": "Ft",
    "default power unit": "225 HP MFWD Tractor",
    "purchase price": 152000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Wagon",
    "field speed (m/h)": 3,
    "field efficiency": 0.63,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Unskilled",
    "shed (ft^2)": 0,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Grain Swather, Self-Propelled; 25 Ft": {
    "key": "Grain Swather, Self-Propelled; 25 Ft",
    "type": "Harvest",
    "name": "Grain Swather, Self-Propelled",
    "size1": 25,
    "unit1": "Ft",
    "default power unit": " None Tractor",
    "purchase price": 204500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 80,
    "default ASABE category": "Windrower (SP)",
    "field speed (m/h)": 5,
    "field efficiency": 0.8,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 345,
    "Notes": "Source: MachData2021  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Hay Baler PTO Twine; 12 Ft": {
    "key": "Hay Baler PTO Twine; 12 Ft",
    "type": "Harvest",
    "name": "Hay Baler PTO Twine",
    "size1": 12,
    "unit1": "Ft",
    "default power unit": "60 HP Tractor",
    "purchase price": 37000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Rectangular baler",
    "field speed (m/h)": 4,
    "field efficiency": 0.75,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 184,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Hay Rake; 30 Ft": {
    "key": "Hay Rake; 30 Ft",
    "type": "Harvest",
    "name": "Hay Rake",
    "size1": 30,
    "unit1": "Ft",
    "default power unit": "40 HP Tractor",
    "purchase price": 31000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 80,
    "default ASABE category": "Side delivery rake",
    "field speed (m/h)": 9,
    "field efficiency": 0.8,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 250,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Large Rectangular Baler; 3x3 ; 20 Ft": {
    "key": "Large Rectangular Baler; 3x3 ; 20 Ft",
    "type": "Harvest",
    "name": "Large Rectangular Baler",
    "size1": 20,
    "unit1": "Ft",
    "size2": "3x3",
    "default power unit": "130 HP MFWD Tractor",
    "purchase price": 155000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 250,
    "default ASABE category": "Large rectangular baler",
    "field speed (m/h)": 6,
    "field efficiency": 0.8,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 250,
    "Notes": "Source: MachData2024  from Lazarus",
    "unit2": ""
  },
  "Large Rectangular Baler; 4x3 ; 20 Ft": {
    "key": "Large Rectangular Baler; 4x3 ; 20 Ft",
    "type": "Harvest",
    "name": "Large Rectangular Baler",
    "size1": 20,
    "unit1": "Ft",
    "size2": "4x3",
    "default power unit": "200 HP MFWD Tractor",
    "purchase price": 192000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 250,
    "default ASABE category": "Large rectangular baler",
    "field speed (m/h)": 6,
    "field efficiency": 0.8,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 250,
    "Notes": "Source: MachData2024  from Lazarus",
    "unit2": ""
  },
  "Moldboard Plow; 6 Bottom; 9 Ft": {
    "key": "Moldboard Plow; 6 Bottom; 9 Ft",
    "type": "Tillage",
    "name": "Moldboard Plow",
    "size1": 9,
    "unit1": "Ft",
    "size2": "6",
    "unit2": "Bottom",
    "default power unit": "130 HP MFWD Tractor",
    "purchase price": 33500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 120,
    "default ASABE category": "Moldboard plows",
    "field speed (m/h)": 4.5,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 132,
    "Notes": "Source: MachData2024  from Lazarus"
  },
  "Moldboard Plow; 8 Bottom; 12 Ft": {
    "key": "Moldboard Plow; 8 Bottom; 12 Ft",
    "type": "Tillage",
    "name": "Moldboard Plow",
    "size1": 12,
    "unit1": "Ft",
    "size2": "8",
    "unit2": "Bottom",
    "default power unit": "200 HP MFWD Tractor",
    "purchase price": 44500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 120,
    "default ASABE category": "Moldboard plows",
    "field speed (m/h)": 4.5,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 150,
    "Notes": "Source: MachData2024  from Lazarus"
  },
  "No-Till Drill; 15 Ft": {
    "key": "No-Till Drill; 15 Ft",
    "type": "Planting",
    "name": "No-Till Drill ",
    "size1": 15,
    "unit1": "Ft",
    "default power unit": "130 HP MFWD Tractor",
    "purchase price": 79000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 80,
    "default ASABE category": "Grain drill",
    "field speed (m/h)": 5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 160,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "No-Till Drill; 20 Ft": {
    "key": "No-Till Drill; 20 Ft",
    "type": "Planting",
    "name": "No-Till Drill ",
    "size1": 20,
    "unit1": "Ft",
    "default power unit": "160 HP MFWD Tractor",
    "purchase price": 72000,
    "list discount": 0.05,
    "expected life (years)": 12,
    "expected use (hr/yr)": 80,
    "default ASABE category": "Grain drill",
    "field speed (m/h)": 5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 185,
    "Notes": "Source: MachData2021  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "No-Till Drill; 25 Ft Fold": {
    "key": "No-Till Drill; 25 Ft Fold",
    "type": "Planting",
    "name": "No-Till Drill ",
    "size1": 25,
    "unit1": "Ft Fold",
    "default power unit": "200 HP MFWD Tractor",
    "purchase price": 80000,
    "list discount": 0.05,
    "expected life (years)": 12,
    "expected use (hr/yr)": 80,
    "default ASABE category": "Grain drill",
    "field speed (m/h)": 5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 230,
    "Notes": "Source: MachData2021  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "No-Till Drill; 30 Ft Fold": {
    "key": "No-Till Drill; 30 Ft Fold",
    "type": "Planting",
    "name": "No-Till Drill ",
    "size1": 30,
    "unit1": "Ft Fold",
    "default power unit": "260 HP MFWD Tractor",
    "purchase price": 92000,
    "list discount": 0.05,
    "expected life (years)": 12,
    "expected use (hr/yr)": 80,
    "default ASABE category": "Grain drill",
    "field speed (m/h)": 5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 250,
    "Notes": "Source: MachData2021  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "No-Till Drill; 40 Ft Fold": {
    "key": "No-Till Drill; 40 Ft Fold",
    "type": "Planting",
    "name": "No-Till Drill ",
    "size1": 30,
    "unit1": "Ft Fold",
    "default power unit": "310 HP 4WD Tractor",
    "purchase price": 104000,
    "list discount": 0.05,
    "expected life (years)": 12,
    "expected use (hr/yr)": 80,
    "default ASABE category": "Grain drill",
    "field speed (m/h)": 5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 300,
    "Notes": "Source: MachData2021  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Offset Disk; 12 Ft": {
    "key": "Offset Disk; 12 Ft",
    "type": "Tillage",
    "name": "Offset Disk",
    "size1": 12,
    "unit1": "Ft",
    "default power unit": "105 HP MFWD Tractor",
    "purchase price": 27500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Heavy Duty disk harrow",
    "field speed (m/h)": 4.5,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 150,
    "Notes": "Old data",
    "size2": "",
    "unit2": ""
  },
  "Presswheel Drill; 16 Ft": {
    "key": "Presswheel Drill; 16 Ft",
    "type": "Planting",
    "name": "Presswheel Drill",
    "size1": 16,
    "unit1": "Ft",
    "default power unit": "105 HP MFWD Tractor",
    "purchase price": 29500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 75,
    "default ASABE category": "Grain drill",
    "field speed (m/h)": 5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 150,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Presswheel Drill; 20 Ft": {
    "key": "Presswheel Drill; 20 Ft",
    "type": "Planting",
    "name": "Presswheel Drill",
    "size1": 20,
    "unit1": "Ft",
    "default power unit": "130 HP MFWD Tractor",
    "purchase price": 35000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 75,
    "default ASABE category": "Grain drill",
    "field speed (m/h)": 5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 185,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Presswheel Drill; 25 Ft": {
    "key": "Presswheel Drill; 25 Ft",
    "type": "Planting",
    "name": "Presswheel Drill",
    "size1": 25,
    "unit1": "Ft",
    "default power unit": "130 HP MFWD Tractor",
    "purchase price": 63000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 75,
    "default ASABE category": "Grain drill",
    "field speed (m/h)": 5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 230,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Presswheel Drill; 30 Ft": {
    "key": "Presswheel Drill; 30 Ft",
    "type": "Planting",
    "name": "Presswheel Drill",
    "size1": 30,
    "unit1": "Ft",
    "default power unit": "160 HP MFWD Tractor",
    "purchase price": 79500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 80,
    "default ASABE category": "Grain drill",
    "field speed (m/h)": 5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.11,
    "labortype": "Skilled",
    "shed (ft^2)": 240,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Ripper/subsoiler; 12.5 Ft": {
    "key": "Ripper/subsoiler; 12.5 Ft",
    "type": "Tillage",
    "name": "V-Ripper",
    "size1": 10,
    "unit1": "Ft",
    "default power unit": "160 HP MFWD Tractor",
    "purchase price": 16500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Chisel plow",
    "field speed (m/h)": 6,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 150,
    "Notes": "Old data",
    "size2": "",
    "unit2": ""
  },
  "Ripper/subsoiler; 17.5 Ft": {
    "key": "Ripper/subsoiler; 17.5 Ft",
    "type": "Tillage",
    "name": "V-Ripper",
    "size1": 17,
    "unit1": "Ft",
    "default power unit": "260 HP MFWD Tractor",
    "purchase price": 22000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Chisel plow",
    "field speed (m/h)": 6,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 240,
    "Notes": "Old data",
    "size2": "",
    "unit2": ""
  },
  "Ripper/subsoiler; 22.5 Ft": {
    "key": "Ripper/subsoiler; 22.5 Ft",
    "type": "Tillage",
    "name": "V-Ripper",
    "size1": 18,
    "unit1": "Ft",
    "default power unit": "360 HP 4WD Tractor",
    "purchase price": 27000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Chisel plow",
    "field speed (m/h)": 6,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 250,
    "Notes": "Old data",
    "size2": "",
    "unit2": ""
  },
  "Ripper/subsoiler; 27.5 Ft": {
    "key": "Ripper/subsoiler; 27.5 Ft",
    "type": "Tillage",
    "name": "V-Ripper",
    "size1": 22.5,
    "unit1": "Ft",
    "default power unit": "425 HP 4WD Tractor",
    "purchase price": 31000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Chisel plow",
    "field speed (m/h)": 6,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 240,
    "Notes": "Old data",
    "size2": "",
    "unit2": ""
  },
  "Rotary Mower/Conditioner; 12 Ft": {
    "key": "Rotary Mower/Conditioner; 12 Ft",
    "type": "Harvest",
    "name": "Rotary Mower/Conditioner",
    "size1": 12,
    "unit1": "Ft",
    "default power unit": "75 HP Tractor",
    "purchase price": 47500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 80,
    "default ASABE category": "Mower-conditioner (rotary)",
    "field speed (m/h)": 7.5,
    "field efficiency": 0.8,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.05,
    "labortype": "Unskilled",
    "shed (ft^2)": 100,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Round Baler w/Bale Wrap; 5x6 ; 20 Ft": {
    "key": "Round Baler w/Bale Wrap; 5x6 ; 20 Ft",
    "type": "Harvest",
    "name": "Round Baler w/Bale Wrap",
    "size1": 20,
    "unit1": "Ft",
    "size2": "5x6",
    "default power unit": "75 HP Tractor",
    "purchase price": 114000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Large round baler",
    "field speed (m/h)": 6,
    "field efficiency": 0.65,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 60,
    "Notes": "Source: MachData2024  from Lazarus",
    "unit2": ""
  },
  "Round Baler; 4x5 ; 20 Ft": {
    "key": "Round Baler; 4x5 ; 20 Ft",
    "type": "Harvest",
    "name": "Round Baler",
    "size1": 20,
    "unit1": "Ft",
    "size2": "4x5",
    "default power unit": "75 HP Tractor",
    "purchase price": 55000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Large round baler",
    "field speed (m/h)": 6,
    "field efficiency": 0.65,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 60,
    "Notes": "Source: MachData2021  from Lazarus",
    "unit2": ""
  },
  "Round Baler; 5x6 ; 20 Ft": {
    "key": "Round Baler; 5x6 ; 20 Ft",
    "type": "Harvest",
    "name": "Round Baler",
    "size1": 20,
    "unit1": "Ft",
    "size2": "5x6",
    "default power unit": "105 HP MFWD Tractor",
    "purchase price": 64000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 200,
    "default ASABE category": "Large round baler",
    "field speed (m/h)": 6,
    "field efficiency": 0.65,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 60,
    "Notes": "Source: MachData2021  from Lazarus",
    "unit2": ""
  },
  "Row Crop Planter; 6 Row; 15 Ft": {
    "key": "Row Crop Planter; 6 Row; 15 Ft",
    "type": "Planting",
    "name": "Row Crop Planter",
    "size1": 15,
    "unit1": "Ft",
    "size2": "6",
    "unit2": "Row",
    "default power unit": "75 HP Tractor",
    "purchase price": 47500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 70,
    "default ASABE category": "Row crop planter",
    "field speed (m/h)": 5.5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.16,
    "labortype": "Skilled",
    "shed (ft^2)": 200,
    "Notes": "Source: MachData2024  from Lazarus"
  },
  "Row Crop Planter; 8 Row; 20 Ft": {
    "key": "Row Crop Planter; 8 Row; 20 Ft",
    "type": "Planting",
    "name": "Row Crop Planter",
    "size1": 20,
    "unit1": "Ft",
    "size2": "8",
    "unit2": "Row",
    "default power unit": "105 HP MFWD Tractor",
    "purchase price": 59000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 70,
    "default ASABE category": "Row crop planter",
    "field speed (m/h)": 5.5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.16,
    "labortype": "Skilled",
    "shed (ft^2)": 200,
    "Notes": "Source: MachData2024  from Lazarus"
  },
  "Row Crop Planter; 12 Row; 30 Ft": {
    "key": "Row Crop Planter; 12 Row; 30 Ft",
    "type": "Planting",
    "name": "Row Crop Planter",
    "size1": 30,
    "unit1": "Ft",
    "size2": "12",
    "unit2": "Row",
    "default power unit": "130 HP MFWD Tractor",
    "purchase price": 136000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 70.00000000000001,
    "default ASABE category": "Row crop planter",
    "field speed (m/h)": 5.5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.16,
    "labortype": "Skilled",
    "shed (ft^2)": 300,
    "Notes": "Source: MachData2024  from Lazarus"
  },
  "Row Crop Planter; 16 Row; 40 Ft": {
    "key": "Row Crop Planter; 16 Row; 40 Ft",
    "type": "Planting",
    "name": "Row Crop Planter",
    "size1": 40,
    "unit1": "Ft",
    "size2": "16",
    "unit2": "Row",
    "default power unit": "200 HP MFWD Tractor",
    "purchase price": 200000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 70,
    "default ASABE category": "Row crop planter",
    "field speed (m/h)": 5.5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.16,
    "labortype": "Skilled",
    "shed (ft^2)": 300,
    "Notes": "Source: MachData2024  from Lazarus"
  },
  "Row Crop Planter; 24 Row; 60 Ft": {
    "key": "Row Crop Planter; 24 Row; 60 Ft",
    "type": "Planting",
    "name": "Row Crop Planter",
    "size1": 60,
    "unit1": "Ft",
    "size2": "24",
    "unit2": "Row",
    "default power unit": "310 HP 4WD Tractor",
    "purchase price": 324000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 70,
    "default ASABE category": "Row crop planter",
    "field speed (m/h)": 5.5,
    "field efficiency": 0.7,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.16,
    "labortype": "Skilled",
    "shed (ft^2)": 300,
    "Notes": "Source: MachData2024  from Lazarus"
  },
  "Row Cultivator; 12 Row; 30 Ft": {
    "key": "Row Cultivator; 12 Row; 30 Ft",
    "type": "CropMaint",
    "name": "Row Cultivator",
    "size1": 30,
    "unit1": "Ft",
    "size2": "12",
    "unit2": "Row",
    "default power unit": "160 HP MFWD Tractor",
    "purchase price": 48000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Row crop cultivator",
    "field speed (m/h)": 5,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.04,
    "labortype": "Unskilled",
    "shed (ft^2)": 140,
    "Notes": "Source: MachData2024  from Lazarus"
  },
  "Stalk Shredder; 20 Ft": {
    "key": "Stalk Shredder; 20 Ft",
    "type": "CropMaint",
    "name": "Stalk Shredder",
    "size1": 20,
    "unit1": "Ft",
    "default power unit": "130 HP MFWD Tractor",
    "purchase price": 40500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Beet topper/stalk chopper",
    "field speed (m/h)": 4,
    "field efficiency": 0.8,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.1,
    "labortype": "Unskilled",
    "shed (ft^2)": 231,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Tandem Disk; 21 Ft Fold": {
    "key": "Tandem Disk; 21 Ft Fold",
    "type": "Tillage",
    "name": "Tandem Disk",
    "size1": 21,
    "unit1": "Ft Fold",
    "default power unit": "160 HP MFWD Tractor",
    "purchase price": 89000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Chisel plow",
    "field speed (m/h)": 6,
    "field efficiency": 0.8,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 260,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Tandem Disk; 30 Ft Fold": {
    "key": "Tandem Disk; 30 Ft Fold",
    "type": "Tillage",
    "name": "Tandem Disk",
    "size1": 30,
    "unit1": "Ft Fold",
    "default power unit": "260 HP MFWD Tractor",
    "purchase price": 129000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Chisel plow",
    "field speed (m/h)": 6,
    "field efficiency": 0.8,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.02,
    "labortype": "Unskilled",
    "shed (ft^2)": 280,
    "Notes": "Source: MachData2024  from Lazarus",
    "size2": "",
    "unit2": ""
  },
  "Vertical Tillage; 15 Ft": {
    "key": "Vertical Tillage; 15 Ft",
    "type": "Tillage",
    "name": "Vertical Tillage",
    "size1": 15,
    "unit1": "Ft",
    "default power unit": "160 HP MFWD Tractor",
    "purchase price": 61000,
    "list discount": 0,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Tandem disk harrow",
    "field speed (m/h)": 9,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.05,
    "labortype": "Unskilled",
    "shed (ft^2)": 200,
    "Notes": "Drew Kientzy research 2023",
    "size2": "",
    "unit2": ""
  },
  "Vertical Tillage; 20 Ft Fold": {
    "key": "Vertical Tillage; 20 Ft Fold",
    "type": "Tillage",
    "name": "Vertical Tillage",
    "size1": 20,
    "unit1": "Ft Fold",
    "default power unit": "200 HP MFWD Tractor",
    "purchase price": 90000,
    "list discount": 0,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Tandem disk harrow",
    "field speed (m/h)": 9,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.05,
    "labortype": "Unskilled",
    "shed (ft^2)": 180,
    "Notes": "Drew Kientzy research 2023",
    "size2": "",
    "unit2": ""
  },
  "Vertical Tillage; 25 Ft Fold": {
    "key": "Vertical Tillage; 25 Ft Fold",
    "type": "Tillage",
    "name": "Vertical Tillage",
    "size1": 25,
    "unit1": "Ft Fold",
    "default power unit": "260 HP MFWD Tractor",
    "purchase price": 115000,
    "list discount": 0.05,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Tandem disk harrow",
    "field speed (m/h)": 9,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.05,
    "labortype": "Unskilled",
    "shed (ft^2)": 200,
    "Notes": "Drew Kientzy research 2023",
    "size2": "",
    "unit2": ""
  },
  "Vertical Tillage; 30 Ft Fold": {
    "key": "Vertical Tillage; 30 Ft Fold",
    "type": "Tillage",
    "name": "Vertical Tillage",
    "size1": 30,
    "unit1": "Ft Fold",
    "default power unit": "310 HP 4WD Tractor",
    "purchase price": 132500,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Tandem disk harrow",
    "field speed (m/h)": 9,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.05,
    "labortype": "Unskilled",
    "shed (ft^2)": 225,
    "Notes": "Drew Kientzy research 2023",
    "size2": "",
    "unit2": ""
  },
  "Vertical Tillage; 40 Ft Fold": {
    "key": "Vertical Tillage; 40 Ft Fold",
    "type": "Tillage",
    "name": "Vertical Tillage",
    "size1": 40,
    "unit1": "Ft Fold",
    "default power unit": "425 HP 4WD Tractor",
    "purchase price": 161000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "default ASABE category": "Tandem disk harrow",
    "field speed (m/h)": 9,
    "field efficiency": 0.85,
    "tractor (hr/impl)": 1,
    "labor (hr/trac)": 1.05,
    "labortype": "Unskilled",
    "shed (ft^2)": 225,
    "Notes": "Drew Kientzy research 2023",
    "size2": "",
    "unit2": ""
  }
};

const ATpower = {
  "40 HP Tractor": {
    "key": "40 HP Tractor",
    "Description": "HP Tractor",
    "HP": 40,
    "purchase price": 33000,
    "list discount": 0,
    "expected life (years)": 12,
    "expected use (hr/yr)": 400,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 92,
    "default ASABE category": "Two wheel drive tractors, under 80 HP",
    "Notes": "Source: MachData2024  from Lazarus",
    "screen": ""
  },
  "60 HP Tractor": {
    "key": "60 HP Tractor",
    "Description": "HP Tractor",
    "HP": 60,
    "purchase price": 37000,
    "list discount": 0,
    "expected life (years)": 12,
    "expected use (hr/yr)": 400,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 104,
    "default ASABE category": "Two wheel drive tractors, under 80 HP",
    "Notes": "Source: MachData2024  from Lazarus",
    "screen": ""
  },
  "75 HP Tractor": {
    "key": "75 HP Tractor",
    "Description": "HP Tractor",
    "HP": 75,
    "purchase price": 65000,
    "list discount": 0.05,
    "expected life (years)": 12,
    "expected use (hr/yr)": 400,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 115,
    "default ASABE category": "Two wheel drive tractors, under 80 HP",
    "Notes": "Source: MachData2024  from Lazarus",
    "screen": ""
  },
  "105 HP MFWD Tractor": {
    "key": "105 HP MFWD Tractor",
    "Description": "HP MFWD Tractor",
    "HP": 105,
    "purchase price": 173000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 450,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 127,
    "default ASABE category": "Mech. front wheel drive tractors",
    "Notes": "Source: MachData2024  from Lazarus",
    "screen": ""
  },
  "130 HP MFWD Tractor": {
    "key": "130 HP MFWD Tractor",
    "Description": "HP MFWD Tractor",
    "HP": 130,
    "purchase price": 239000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 450,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 130,
    "default ASABE category": "Mech. front wheel drive tractors",
    "Notes": "Source: MachData2024  from Lazarus",
    "screen": ""
  },
  "130 HP Self Propelled|termination.chemical": {
    "key": "130 HP Self Propelled",
    "Description": "HP Self Propelled",
    "HP": 130,
    "purchase price": 673000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 100,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "default ASABE category": "None",
    "Notes": "Source: MachData2024  from Lazarus",
    "screen": "termination.chemical",
    "shed (ft^2)": ""
  },
  "160 HP MFWD Tractor": {
    "key": "160 HP MFWD Tractor",
    "Description": "HP MFWD Tractor",
    "HP": 160,
    "purchase price": 299000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 500,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 200,
    "default ASABE category": "Mech. front wheel drive tractors",
    "Notes": "Source: MachData2024  from Lazarus",
    "screen": ""
  },
  "200 HP MFWD Tractor": {
    "key": "200 HP MFWD Tractor",
    "Description": "HP MFWD Tractor",
    "HP": 200,
    "purchase price": 387000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 500,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 230,
    "default ASABE category": "Mech. front wheel drive tractors",
    "Notes": "Source: MachData2024  from Lazarus",
    "screen": ""
  },
  "225 HP MFWD Tractor": {
    "key": "225 HP MFWD Tractor",
    "Description": "HP MFWD Tractor",
    "HP": 225,
    "purchase price": 402000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 400,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 230,
    "default ASABE category": "Mech. front wheel drive tractors",
    "Notes": "Source: MachData2024  from Lazarus",
    "screen": ""
  },
  "260 HP MFWD Tractor": {
    "key": "260 HP MFWD Tractor",
    "Description": "HP MFWD Tractor",
    "HP": 260,
    "purchase price": 480000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 400,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 230,
    "default ASABE category": "Four wheel drive tractors & crawlers",
    "Notes": "Source: MachData2024  from Lazarus",
    "screen": ""
  },
  "275 HP Combine|hide": {
    "key": "275 HP Combine",
    "Description": "HP Combine",
    "HP": 275,
    "purchase price": 447000,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 400,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 400,
    "default ASABE category": "Combine (self propelled)",
    "Notes": "Source: MachData2024  from Lazarus",
    "screen": "hide"
  },
  "310 HP 4WD Tractor": {
    "key": "310 HP 4WD Tractor",
    "Description": "HP 4WD Tractor",
    "HP": 310,
    "purchase price": 491000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 400,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 250,
    "default ASABE category": "Four wheel drive tractors & crawlers",
    "Notes": "Source: MachData2024  from Lazarus",
    "screen": ""
  },
  "360 HP 4WD Tractor": {
    "key": "360 HP 4WD Tractor",
    "Description": "HP 4WD Tractor",
    "HP": 360,
    "purchase price": 451000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 400,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 250,
    "default ASABE category": "Four wheel drive tractors & crawlers",
    "Notes": "Source: MachData2024  from Lazarus",
    "screen": ""
  },
  "375 HP Combine|hide": {
    "key": "375 HP Combine",
    "Description": "HP Combine",
    "HP": 375,
    "purchase price": 525000,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 400,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 500,
    "default ASABE category": "Combine (self propelled)",
    "Notes": "Source: MachData2024  from Lazarus",
    "screen": "hide"
  },
  "400 HP SP Forage Harvester Base Unit|hide": {
    "key": "400 HP SP Forage Harvester Base Unit",
    "Description": "HP SP Forage Harvester Base Unit",
    "HP": 400,
    "purchase price": 524000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 350,
    "fuel use (gal/PTO hp/hr)": 0.024,
    "shed (ft^2)": 500,
    "default ASABE category": "Forage harvester (SP)",
    "Notes": "Source: MachData2024  from Lazarus",
    "screen": "hide"
  },
  "425 HP 4WD Tractor": {
    "key": "425 HP 4WD Tractor",
    "Description": "HP 4WD Tractor",
    "HP": 425,
    "purchase price": 536000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 400,
    "fuel use (gal/PTO hp/hr)": 0.044,
    "shed (ft^2)": 250,
    "default ASABE category": "Four wheel drive tractors & crawlers",
    "Notes": "Source: MachData2024  from Lazarus",
    "screen": ""
  },
  "440 HP Combine|hide": {
    "key": "440 HP Combine",
    "Description": "HP Combine",
    "HP": 440,
    "purchase price": 557000,
    "list discount": 0.2,
    "expected life (years)": 12,
    "expected use (hr/yr)": 400,
    "fuel use (gal/PTO hp/hr)": 0.038305882,
    "shed (ft^2)": 500,
    "default ASABE category": "Combine (self propelled)",
    "Notes": "Source: MachData2024  from Lazarus",
    "screen": "hide"
  },
  "625 HP SP Forage Harvester Base Unit|hide": {
    "key": "625 HP SP Forage Harvester Base Unit",
    "Description": "HP SP Forage Harvester Base Unit",
    "HP": 625,
    "purchase price": 630000,
    "list discount": 0.1,
    "expected life (years)": 12,
    "expected use (hr/yr)": 350,
    "fuel use (gal/PTO hp/hr)": 0.024,
    "shed (ft^2)": 500,
    "default ASABE category": "Forage harvester (SP)",
    "Notes": "Source: MachData2024  from Lazarus",
    "screen": "hide"
  }
};

const ATseedList = {
  "Alfalfa": {
    "key": "Alfalfa",
    "seedingRate": 20,
    "price": 4.53,
    "NCredit": 40,
    "type": "Legume",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "erosion": "",
    "legume": ""
  },
  "Barley": {
    "key": "Barley",
    "seedingRate": 75,
    "price": 0.5,
    "type": "Grass",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Brassica, Forage": {
    "key": "Brassica, Forage",
    "seedingRate": 3,
    "price": 3.57,
    "NCredit": 10,
    "type": "Brassica",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "erosion": "",
    "legume": ""
  },
  "Brome": {
    "key": "Brome",
    "seedingRate": 20,
    "price": 3.79,
    "type": "Grass",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Buckwheat": {
    "key": "Buckwheat",
    "seedingRate": 60,
    "price": 1.49,
    "type": "Broadleaf",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Cereal Rye": {
    "key": "Cereal Rye",
    "seedingRate": 80,
    "price": 0.58,
    "NCredit": 0,
    "erosion": true,
    "type": "Grass",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "legume": ""
  },
  "Clover": {
    "key": "Clover",
    "seedingRate": 10,
    "price": 3.33,
    "legume": true,
    "NCredit": 30,
    "type": "Legume",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "erosion": ""
  },
  "Cowpea": {
    "key": "Cowpea",
    "seedingRate": 70,
    "price": 1.36,
    "NCredit": 35,
    "type": "Legume",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "erosion": "",
    "legume": ""
  },
  "Fescue": {
    "key": "Fescue",
    "seedingRate": 20,
    "price": 3.31,
    "type": "Grass",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Millet": {
    "key": "Millet",
    "seedingRate": 20,
    "price": 1.33,
    "type": "Grass",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Mustard": {
    "key": "Mustard",
    "seedingRate": 10,
    "price": 2.88,
    "type": "Brassica",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Oats": {
    "key": "Oats",
    "seedingRate": 100,
    "price": 0.5,
    "NCredit": 0,
    "erosion": true,
    "type": "Grass",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "legume": ""
  },
  "Pea": {
    "key": "Pea",
    "seedingRate": 80,
    "price": 0.79,
    "NCredit": 30,
    "type": "Legume",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "erosion": "",
    "legume": ""
  },
  "Radish": {
    "key": "Radish",
    "seedingRate": 12,
    "price": 2.77,
    "NCredit": 10,
    "type": "Brassica",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "erosion": "",
    "legume": ""
  },
  "Rapeseed, Forage": {
    "key": "Rapeseed, Forage",
    "seedingRate": 8,
    "price": 1.1,
    "NCredit": 10,
    "type": "Brassica",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "erosion": "",
    "legume": ""
  },
  "Ryegrass, Annual": {
    "key": "Ryegrass, Annual",
    "seedingRate": 15,
    "price": 0.98,
    "NCredit": 0,
    "erosion": true,
    "type": "Grass",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "legume": ""
  },
  "Ryegrass, Perennial": {
    "key": "Ryegrass, Perennial",
    "seedingRate": 20,
    "price": 2.77,
    "NCredit": 0,
    "erosion": true,
    "type": "Grass",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "legume": ""
  },
  "Sorghum": {
    "key": "Sorghum",
    "seedingRate": 25,
    "price": 0.93,
    "type": "Grass",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Sorghum-sudangrass": {
    "key": "Sorghum-sudangrass",
    "seedingRate": 40,
    "price": 1.31,
    "type": "Grass",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Soybeans": {
    "key": "Soybeans",
    "seedingRate": 50,
    "price": 1.28,
    "NCredit": 15,
    "type": "Legume",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "erosion": "",
    "legume": ""
  },
  "Sudangrass": {
    "key": "Sudangrass",
    "seedingRate": 25,
    "price": 1.33,
    "type": "Grass",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Sunflower": {
    "key": "Sunflower",
    "seedingRate": 5,
    "price": 1.97,
    "type": "Broadleaf",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Sunn Hemp": {
    "key": "Sunn Hemp",
    "seedingRate": 30,
    "price": 1.89,
    "NCredit": 25,
    "type": "Legume",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "erosion": "",
    "legume": ""
  },
  "Teff": {
    "key": "Teff",
    "seedingRate": 8,
    "price": 2.87,
    "type": "Grass",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Triticale": {
    "key": "Triticale",
    "seedingRate": 90,
    "price": 0.6,
    "type": "Grass",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "NCredit": "",
    "erosion": "",
    "legume": ""
  },
  "Turnip, Forage": {
    "key": "Turnip, Forage",
    "seedingRate": 8,
    "price": 2.29,
    "NCredit": 10,
    "type": "Brassica",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "erosion": "",
    "legume": ""
  },
  "Vetch, Hairy": {
    "key": "Vetch, Hairy",
    "seedingRate": 17,
    "price": 2.28,
    "NCredit": 30,
    "type": "Legume",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "erosion": "",
    "legume": ""
  },
  "Wheat, Spring": {
    "key": "Wheat, Spring",
    "seedingRate": 120,
    "price": 0.5,
    "NCredit": 0,
    "erosion": true,
    "type": "Grass",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "legume": ""
  },
  "Wheat, Winter": {
    "key": "Wheat, Winter",
    "seedingRate": 90,
    "price": 0.36,
    "NCredit": 0,
    "erosion": true,
    "type": "Grass",
    "Notes": "Updated 8/15/24, average of 4 internet seed suppliers",
    "legume": ""
  }
};

const ATstateRegions = {
  "ALABAMA": {
    "key": "ALABAMA",
    "ccRegion": "southern",
    "USDARegion": "South"
  },
  "ALASKA": {
    "key": "ALASKA",
    "USDARegion": "None",
    "ccRegion": ""
  },
  "ARIZONA": {
    "key": "ARIZONA",
    "ccRegion": "western",
    "USDARegion": "West"
  },
  "ARKANSAS": {
    "key": "ARKANSAS",
    "ccRegion": "southern",
    "USDARegion": "South"
  },
  "CALIFORNIA": {
    "key": "CALIFORNIA",
    "ccRegion": "western",
    "USDARegion": "West"
  },
  "COLORADO": {
    "key": "COLORADO",
    "ccRegion": "western",
    "USDARegion": "West"
  },
  "CONNECTICUT": {
    "key": "CONNECTICUT",
    "ccRegion": "northeast",
    "USDARegion": "Atlantic"
  },
  "DELAWARE": {
    "key": "DELAWARE",
    "ccRegion": "northeast",
    "USDARegion": "Atlantic"
  },
  "DISTRICT OF COLUMBIA": {
    "key": "DISTRICT OF COLUMBIA",
    "ccRegion": "northeast",
    "USDARegion": "Atlantic"
  },
  "FLORIDA": {
    "key": "FLORIDA",
    "ccRegion": "southern",
    "USDARegion": "South"
  },
  "GEORGIA": {
    "key": "GEORGIA",
    "ccRegion": "southern",
    "USDARegion": "South"
  },
  "HAWAII": {
    "key": "HAWAII",
    "USDARegion": "None",
    "ccRegion": ""
  },
  "IDAHO": {
    "key": "IDAHO",
    "ccRegion": "western",
    "USDARegion": "West"
  },
  "ILLINOIS": {
    "key": "ILLINOIS",
    "ccRegion": "midwest",
    "USDARegion": "Midwest"
  },
  "INDIANA": {
    "key": "INDIANA",
    "ccRegion": "midwest",
    "USDARegion": "Midwest"
  },
  "IOWA": {
    "key": "IOWA",
    "ccRegion": "midwest",
    "USDARegion": "Midwest"
  },
  "KANSAS": {
    "key": "KANSAS",
    "ccRegion": "western",
    "USDARegion": "Plains"
  },
  "KENTUCKY": {
    "key": "KENTUCKY",
    "ccRegion": "midwest",
    "USDARegion": "Atlantic"
  },
  "LOUISIANA": {
    "key": "LOUISIANA",
    "ccRegion": "southern",
    "USDARegion": "South"
  },
  "MAINE": {
    "key": "MAINE",
    "ccRegion": "northeast",
    "USDARegion": "Atlantic"
  },
  "MARYLAND": {
    "key": "MARYLAND",
    "ccRegion": "northeast",
    "USDARegion": "Atlantic"
  },
  "MASSACHUSETTS": {
    "key": "MASSACHUSETTS",
    "ccRegion": "northeast",
    "USDARegion": "Atlantic"
  },
  "MICHIGAN": {
    "key": "MICHIGAN",
    "ccRegion": "midwest",
    "USDARegion": "Midwest"
  },
  "MINNESOTA": {
    "key": "MINNESOTA",
    "ccRegion": "midwest",
    "USDARegion": "Midwest"
  },
  "MISSISSIPPI": {
    "key": "MISSISSIPPI",
    "ccRegion": "southern",
    "USDARegion": "South"
  },
  "MISSOURI": {
    "key": "MISSOURI",
    "ccRegion": "midwest",
    "USDARegion": "Midwest"
  },
  "MONTANA": {
    "key": "MONTANA",
    "ccRegion": "western",
    "USDARegion": "West"
  },
  "NEBRASKA": {
    "key": "NEBRASKA",
    "ccRegion": "western",
    "USDARegion": "Plains"
  },
  "NEVADA": {
    "key": "NEVADA",
    "ccRegion": "western",
    "USDARegion": "West"
  },
  "NEW HAMPSHIRE": {
    "key": "NEW HAMPSHIRE",
    "ccRegion": "northeast",
    "USDARegion": "Atlantic"
  },
  "NEW JERSEY": {
    "key": "NEW JERSEY",
    "ccRegion": "northeast",
    "USDARegion": "Atlantic"
  },
  "NEW MEXICO": {
    "key": "NEW MEXICO",
    "ccRegion": "western",
    "USDARegion": "West"
  },
  "NEW YORK": {
    "key": "NEW YORK",
    "ccRegion": "northeast",
    "USDARegion": "Atlantic"
  },
  "NORTH CAROLINA": {
    "key": "NORTH CAROLINA",
    "ccRegion": "southern",
    "USDARegion": "Atlantic"
  },
  "NORTH DAKOTA": {
    "key": "NORTH DAKOTA",
    "ccRegion": "western",
    "USDARegion": "Plains"
  },
  "OHIO": {
    "key": "OHIO",
    "ccRegion": "midwest",
    "USDARegion": "Midwest"
  },
  "OKLAHOMA": {
    "key": "OKLAHOMA",
    "ccRegion": "southern",
    "USDARegion": "Plains"
  },
  "OREGON": {
    "key": "OREGON",
    "ccRegion": "western",
    "USDARegion": "West"
  },
  "PENNSYLVANIA": {
    "key": "PENNSYLVANIA",
    "ccRegion": "northeast",
    "USDARegion": "Atlantic"
  },
  "RHODE ISLAND": {
    "key": "RHODE ISLAND",
    "ccRegion": "northeast",
    "USDARegion": "Atlantic"
  },
  "SOUTH CAROLINA": {
    "key": "SOUTH CAROLINA",
    "ccRegion": "southern",
    "USDARegion": "South"
  },
  "SOUTH DAKOTA": {
    "key": "SOUTH DAKOTA",
    "ccRegion": "western",
    "USDARegion": "Plains"
  },
  "TENNESSEE": {
    "key": "TENNESSEE",
    "ccRegion": "southern",
    "USDARegion": "Atlantic"
  },
  "TEXAS": {
    "key": "TEXAS",
    "ccRegion": "southern",
    "USDARegion": "Plains"
  },
  "UTAH": {
    "key": "UTAH",
    "ccRegion": "western",
    "USDARegion": "West"
  },
  "VERMONT": {
    "key": "VERMONT",
    "ccRegion": "northeast",
    "USDARegion": "Atlantic"
  },
  "VIRGINIA": {
    "key": "VIRGINIA",
    "ccRegion": "southern",
    "USDARegion": "Atlantic"
  },
  "WASHINGTON": {
    "key": "WASHINGTON",
    "ccRegion": "western",
    "USDARegion": "West"
  },
  "WEST VIRGINIA": {
    "key": "WEST VIRGINIA",
    "ccRegion": "northeast",
    "USDARegion": "Atlantic"
  },
  "WISCONSIN": {
    "key": "WISCONSIN",
    "ccRegion": "midwest",
    "USDARegion": "Midwest"
  },
  "WYOMING": {
    "key": "WYOMING",
    "ccRegion": "western",
    "USDARegion": "West"
  }
};

const ATcommodities = {
  "Corn": {
    "key": "Corn",
    "price": 4.66,
    "one year": 0.005200000000000001,
    "three year": 0.0176,
    "five year": 0.03,
    "Notes": "Price is 2024 RMA springtime price; % change is from SARE publication by Myers.",
    "order": 1,
    "yield": "160"
  },
  "Soybeans": {
    "key": "Soybeans",
    "price": 11.55,
    "one year": 0.0212,
    "three year": 0.0354,
    "five year": 0.0496,
    "Notes": "Price is 2024 RMA springtime price; % change is from SARE publication by Myers.",
    "order": 2,
    "yield": "50"
  },
  "Wheat": {
    "key": "Wheat",
    "price": 5.97,
    "Notes": "Price is 2024 RMA fall price",
    "order": 3,
    "one year": "",
    "three year": "",
    "five year": "",
    "yield": ""
  },
  "Grain Sorghum (milo)": {
    "key": "Grain Sorghum (milo)",
    "price": 4.67,
    "Notes": "Price is 2024 RMA springtime price",
    "order": 4,
    "one year": "",
    "three year": "",
    "five year": "",
    "yield": ""
  },
  "Cotton": {
    "key": "Cotton",
    "price": 0.83,
    "Notes": "Price is 2024 RMA springtime price for SE US",
    "order": 5,
    "one year": "",
    "three year": "",
    "five year": "",
    "yield": ""
  },
  "Rice": {
    "key": "Rice",
    "price": 0.24,
    "Notes": "Price is 2024RMA springtime price for SE US short/med grain rice",
    "order": 6,
    "one year": "",
    "three year": "",
    "five year": "",
    "yield": ""
  },
  "Sunflower": {
    "key": "Sunflower",
    "price": 0.25,
    "Notes": "Price is 2024 RMA springtime price (Avg of oil and confectionary)",
    "order": 7,
    "one year": "",
    "three year": "",
    "five year": "",
    "yield": ""
  },
  "Canola": {
    "key": "Canola",
    "price": 0.21,
    "Notes": "Price is 2024 RMA fall price",
    "order": 8,
    "one year": "",
    "three year": "",
    "five year": "",
    "yield": ""
  }
};

const ATeqip = {
  "AL": {
    "key": "AL",
    "basic": 61.85,
    "multiple": 77.28,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "AR": {
    "key": "AR",
    "basic": 48.07,
    "multiple": 60.42,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "CT": {
    "key": "CT",
    "basic": 61.88,
    "multiple": 77.31,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "DC": {
    "key": "DC",
    "basic": 62.09,
    "multiple": 77.52,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "DE": {
    "key": "DE",
    "basic": 65.73,
    "multiple": 81.16,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "FL": {
    "key": "FL",
    "basic": 61.52,
    "multiple": 92.34,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "GA": {
    "key": "GA",
    "basic": 60.86,
    "multiple": 76.29,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "IA": {
    "key": "IA",
    "basic": 61.5,
    "multiple": 76.93,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "IL": {
    "key": "IL",
    "basic": 62.15,
    "multiple": 77.58,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "IN": {
    "key": "IN",
    "basic": 61.67,
    "multiple": 77.1,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "KS": {
    "key": "KS",
    "basic": 62.25,
    "multiple": 77.68,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "KY": {
    "key": "KY",
    "basic": 62.34,
    "multiple": 77.76,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "LA": {
    "key": "LA",
    "basic": 59.68,
    "multiple": 75.11,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "MA": {
    "key": "MA",
    "basic": 61.79,
    "multiple": 77.22,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "MD": {
    "key": "MD",
    "basic": 61.92,
    "multiple": 77.34,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "ME": {
    "key": "ME",
    "basic": 61.66,
    "multiple": 77.09,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "MI": {
    "key": "MI",
    "basic": 61.95,
    "multiple": 77.38,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "MN": {
    "key": "MN",
    "basic": 32.97,
    "multiple": 66.95,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "MO": {
    "key": "MO",
    "basic": 62.45,
    "multiple": 62.45,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "MS": {
    "key": "MS",
    "basic": 61.66,
    "multiple": 77.08,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "NC": {
    "key": "NC",
    "basic": 61.99,
    "multiple": 77.42,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "NE": {
    "key": "NE",
    "basic": 40.97,
    "multiple": 51.25,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "NH": {
    "key": "NH",
    "basic": 61.68,
    "multiple": 77.1,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "NJ": {
    "key": "NJ",
    "basic": 61.45,
    "multiple": 76.88,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "NY": {
    "key": "NY",
    "basic": 64.01,
    "multiple": 79.44,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "OH": {
    "key": "OH",
    "basic": 60.64,
    "multiple": 60.64,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "PA": {
    "key": "PA",
    "basic": 64.2,
    "multiple": 79.63,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "RI": {
    "key": "RI",
    "basic": 62.15,
    "multiple": 77.58,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "SC": {
    "key": "SC",
    "basic": 62.02,
    "multiple": 77.45,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "TN": {
    "key": "TN",
    "basic": 61.62,
    "multiple": 77.05,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "VA": {
    "key": "VA",
    "basic": 74.86,
    "multiple": 93.38,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "VT": {
    "key": "VT",
    "basic": 61.68,
    "multiple": 77.11,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "WI": {
    "key": "WI",
    "basic": 61.84,
    "multiple": 77.26,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  },
  "WV": {
    "key": "WV",
    "basic": 62.09,
    "multiple": 77.51,
    "Notes": "2024 EQIP Practice 340 rates from USDA pubs"
  }
};

const ATerosionControl = {
  "Dozer": {
    "key": "Dozer",
    "cost": 175,
    "Notes": "Median 2024 charge for Bulldozing on ISU Custom Rates, assumed 10 ft blade"
  },
  "Skid steer": {
    "key": "Skid steer",
    "cost": 100,
    "Notes": "median 2022 rate on MO Custom rate survey"
  },
  "Trackhoe": {
    "key": "Trackhoe",
    "cost": 120,
    "Notes": "Median 2024 charge for Backhoeing on ISU Custom Rates"
  }
};

export const db = {
  coefficients: ATcoefficients,
  rates: ATrates,
  costDefaults: ATcostDefaults,
  herbicides: ATherbicides,
  implements: ATimplements,
  power: ATpower,
  seedList: ATseedList,
  stateRegions: ATstateRegions,
  commodities: ATcommodities,
  eqip: ATeqip,
  erosionControl: ATerosionControl,
};
